export const notes = [
	{ slug: 'attend/10-year-plan', title: '10-year Plan' },
	{ slug: 'attend/100-things-to-do', title: '100 Things to Do' },
	{
		slug: 'attend/50q-for-cofounders',
		title: '50 Questions for Aspiring Founders to Ask Each Other',
	},
	{
		slug: 'attend/a-loopy-model-of-reality',
		title: 'A Loopy Model of Reality',
	},
	{ slug: 'attend/a-manifesto', title: 'A Manifesto' },
	{ slug: 'attend/a-personal-evaluation', title: 'A Personal Evaluation' },
	{ slug: 'attend/a-revolution-is-rising', title: 'A Revolution Is Rising' },
	{ slug: 'attend/aaa', title: 'AAA' },
	{ slug: 'attend/acceptance', title: 'Acceptance' },
	{ slug: 'attend/actualization', title: 'Actualization' },
	{ slug: 'attend/affinity', title: 'Affinity' },
	{
		slug: 'attend/alan-watts-serious-philosophical-questions',
		title: 'The Serious Philosophical Questions',
	},
	{ slug: 'attend/always-be-asking', title: 'Always Be Asking' },
	{ slug: 'attend/an-origin-story', title: 'An Origin Story' },
	{ slug: 'attend/androcracy', title: 'androcracy' },
	{ slug: 'attend/anger', title: 'anger' },
	{ slug: 'attend/answers', title: 'Answers' },
	{ slug: 'attend/antonio-damasio', title: 'Antonio Damasio' },
	{ slug: 'attend/april-22nd-2018', title: 'April 22nd, 2018' },
	{
		slug: 'attend/articles-on-consciousness-from-scientific-periodicals',
		title: 'Articles on consciousness from scientific periodicals',
	},
	{ slug: 'attend/as-within-so-without', title: 'As within, so without' },
	{ slug: 'attend/asking-why---a-memoir', title: 'Whatever the Question…' },
	{ slug: 'attend/atmanaut/a-call-to-un-ism', title: 'A Call to Un-ism' },
	{
		slug: 'attend/atmanaut/a-monorepo-theory-of-otherhood',
		title: 'A Theory of Otherhood and the Monorepo',
	},
	{ slug: 'attend/atmanaut/about-atmanaut', title: 'About Atmanaut' },
	{
		slug: 'attend/atmanaut/an-atlas-for-we-who-ask-why',
		title: 'An Atlas for We Who Ask "Why?"',
	},
	{ slug: 'attend/atmanaut/atmanaut-README', title: 'Atmanaut.me README' },
	{ slug: 'attend/atmanaut/atmanaut-home-poems', title: 'Atmanaut Home Poems' },
	{ slug: 'attend/atmanaut/atmanaut-todo', title: 'Atmanaut Todo' },
	{
		slug: 'attend/atmanaut/automatons-4-life',
		title: "It's Never Too Early For Immortality",
	},
	{
		slug: 'attend/atmanaut/cosmological-nihilism',
		title: 'Cosmology - Nihilism or Mysticism',
	},
	{
		slug: 'attend/atmanaut/create-a-preact-on-parcel-bundler-web-app-dev-build',
		title: 'Create a Preact-on-Parcel SPA in a Jiffy',
	},
	{
		slug: 'attend/atmanaut/explanation-vs-description',
		title: 'Explanation vs Description',
	},
	{
		slug: 'attend/atmanaut/forest-an-organic-social-network-design',
		title: 'Forest - An Organic Social Network Design',
	},
	{
		slug: 'attend/atmanaut/how-i-built-this',
		title: 'Building Atmanaut - How This Happened',
	},
	{
		slug: 'attend/atmanaut/how-to-go-where-it-is-nice',
		title: 'How to Go Where It Is Nice',
	},
	{
		slug: 'attend/atmanaut/how-to-lose-your-mind-and-find-ourself',
		title: 'How to Lose Our Minds',
	},
	{
		slug: 'attend/atmanaut/i-ching-and-the-elements-of-time',
		title: 'I Ching and the Elements of Time',
	},
	{
		slug:
			'attend/atmanaut/is-that-a-simulated-fork-in-the-real-path-or-a-real-fork-in-the-simulated-path',
		title:
			'Is That A Simulated Fork in the Real Path or a Real Fork in the Simulated Path?',
	},
	{
		slug: 'attend/atmanaut/primed-to-fall-in-love',
		title: 'Primed To Fall In Love',
	},
	{
		slug: 'attend/atmanaut/robber-baron-or-the-head-judgmeister',
		title: 'Robber Baron or the Head Judgmeister',
	},
	{
		slug: 'attend/atmanaut/sacred-caring-doughnut-economics',
		title: 'Sacred Caring Doughnut Economics',
	},
	{ slug: 'attend/atmanaut/seahorses', title: 'Seahorsing' },
	{ slug: 'attend/atmanaut/so-many-questions', title: 'So Many Questions' },
	{ slug: 'attend/atmanaut/the-shape-of-me', title: 'The Shape of Me' },
	{ slug: 'attend/atmanaut/walks-of-life', title: 'Walks of Life' },
	{
		slug: 'attend/atmanaut/well-being-pendulum',
		title: 'Swinging on the Well-Being Pendulum',
	},
	{ slug: 'attend/atmanaut/wellthy truthy', title: 'Wellthy Truthy' },
	{ slug: 'attend/atmanaut/wind-chiming', title: 'Wind Chiming' },
	{
		slug: 'attend/atmanaut/write-it-once-publish-it-everywhere',
		title: 'Write it Once, Publish it Everywhere',
	},
	{ slug: 'attend/atmanaut', title: 'Atmanaut' },
	{ slug: 'attend/atmanautica', title: 'Atmanautica' },
	{
		slug: 'attend/attention-intent-action-result',
		title: 'Attention Intent Action Result',
	},
	{ slug: 'attend/attention', title: 'Attention' },
	{ slug: 'attend/aum', title: 'AUM' },
	{ slug: 'attend/autorehab', title: 'Autorehab' },
	{ slug: 'attend/awareness', title: 'Awareness' },
	{ slug: 'attend/becoming', title: 'Becoming' },
	{ slug: 'attend/being', title: 'being' },
	{ slug: 'attend/belief', title: 'belief' },
	{ slug: 'attend/big-hard-questions', title: 'Big hard questions' },
	{ slug: 'attend/big-toe', title: 'Big T.O.E.' },
	{ slug: 'attend/bliss', title: 'Bliss' },
	{ slug: 'attend/bodhisattva', title: 'Bodhisattva' },
	{ slug: 'attend/body', title: 'Body' },
	{ slug: 'attend/bound', title: 'bound' },
	{ slug: 'attend/brain-as-antenna', title: 'Brain as Antenna' },
	{ slug: 'attend/brain-as-mind', title: 'Brain As Mind' },
	{ slug: 'attend/brain', title: 'Brain' },
	{ slug: 'attend/brand', title: 'Atmanautica branding' },
	{ slug: 'attend/breathe-and-stop', title: 'Breathe and Stop' },
	{ slug: 'attend/breathe', title: 'Breathe' },
	{ slug: 'attend/causality', title: 'Causality' },
	{ slug: 'attend/chakra', title: 'Chakra' },
	{ slug: 'attend/chaos', title: 'chaos' },
	{ slug: 'attend/cnxns', title: 'CNXNS' },
	{ slug: 'attend/cognition', title: 'Cognition' },
	{ slug: 'attend/compassion', title: 'Compassion' },
	{ slug: 'attend/complexity', title: 'Complexity science' },
	{ slug: 'attend/computation', title: 'Computation' },
	{ slug: 'attend/conscious-loving---hendricks', title: 'Conscious Loving' },
	{ slug: 'attend/consciousness-evolved', title: 'Consciousness, evolved' },
	{
		slug: 'attend/consciousness-vs-self-consciousness',
		title: 'Consciousness Vs. Self Consciousness',
	},
	{ slug: 'attend/consciousness', title: 'Consciousness' },
	{ slug: 'attend/consent', title: 'Consent' },
	{ slug: 'attend/constructor-theory', title: 'Constructor Theory' },
	{ slug: 'attend/consumption', title: 'Consumption' },
	{
		slug: 'attend/contrary-to-popular-belief',
		title: 'Contrary to popular belief',
	},
	{ slug: 'attend/control', title: 'Control' },
	{ slug: 'attend/cosmos', title: 'Cosmos and Quanta' },
	{
		slug: 'attend/covid-statistic-interpretation-science-pseudoscience',
		title: 'COVID Statistic Interpretation, Science, Pseudoscience',
	},
	{ slug: 'attend/creativity', title: 'creativity' },
	{ slug: 'attend/dark-energy', title: 'dark energy' },
	{ slug: 'attend/data', title: 'data' },
	{ slug: 'attend/death', title: 'Death' },
	{ slug: 'attend/deja-vu', title: 'Deja vu' },
	{ slug: 'attend/delusion', title: 'delusion' },
	{ slug: 'attend/depression', title: 'depression' },
	{
		slug: 'attend/determinism-vs-free-will',
		title: 'Determinism vs. Free Will',
	},
	{ slug: 'attend/disease', title: 'disease' },
	{ slug: 'attend/dmt', title: 'DMT' },
	{ slug: 'attend/dogma', title: 'Dogma and Belief' },
	{ slug: 'attend/domain-of-possibility', title: 'Domain of Possibility' },
	{ slug: 'attend/dr-healhurts-wheel', title: "Dr. Healhurt's Wheel" },
	{
		slug: 'attend/dreaming-awake-at-the-end-of-time',
		title: 'Dreaming Awake at the End of Time',
	},
	{ slug: 'attend/dreams', title: 'Dreams' },
	{ slug: 'attend/drive', title: 'Drive' },
	{ slug: 'attend/dualism', title: 'Dualism' },
	{ slug: 'attend/economic-mindset', title: 'Economic Mindset' },
	{ slug: 'attend/ego', title: 'Ego' },
	{ slug: 'attend/emotion', title: 'Emotion' },
	{ slug: 'attend/empathy', title: 'Empathy' },
	{ slug: 'attend/energy', title: 'Energy' },
	{ slug: 'attend/entropy', title: 'Entropy' },
	{ slug: 'attend/evolution', title: 'Evolution' },
	{ slug: 'attend/existence', title: 'Existence' },
	{ slug: 'attend/existing-as-sovereign', title: 'Existing as Sovereign' },
	{ slug: 'attend/expectation', title: 'expectation' },
	{ slug: 'attend/experience', title: 'experience' },
	{ slug: 'attend/experiences', title: 'experiences' },
	{
		slug:
			'attend/experiencing-the-domain-of-possibilities-from-manifested-reality',
		title: 'Experiencing The Domain Of Possibilities From Manifested Reality',
	},
	{ slug: 'attend/ez-water', title: 'EZ water' },
	{ slug: 'attend/fail-school-plan', title: 'Fail School Ideas' },
	{ slug: 'attend/fail-school', title: 'Fail School' },
	{ slug: 'attend/faq', title: 'FAQ' },
	{ slug: 'attend/fear', title: 'Fear' },
	{
		slug: 'attend/feedback-loops-of-the-mind-and-in-time',
		title: 'Feedback Loops Of The Mind And In Time',
	},
	{ slug: 'attend/feel', title: 'feel' },
	{ slug: 'attend/feeling', title: 'feeling' },
	{ slug: 'attend/flow', title: 'flow' },
	{ slug: 'attend/food', title: 'Food' },
	{
		slug: 'attend/four-agreements---don-miguel-ruiz',
		title: 'Four Agreements',
	},
	{ slug: 'attend/free-will', title: 'Free Will' },
	{ slug: 'attend/fresh-macbook-m1-setup' },
	{ slug: 'attend/full-body-smile', title: 'Full Body Smile' },
	{ slug: 'attend/full-smile-in-a-page', title: 'Full Smile in a page' },
	{ slug: 'attend/full-smile-in-a-pager', title: 'Full Smile in a page' },
	{ slug: 'attend/full-smile-synopsis-v1', title: 'Full Smile Synopsis' },
	{ slug: 'attend/full-smile-synopsis-v2', title: 'Full Smile Synopsis, v2' },
	{ slug: 'attend/full-smile-synopsis-v3', title: 'Full Smile Synopsis, v3' },
	{ slug: 'attend/full-smile', title: 'Full Smile' },
	{ slug: 'attend/future-authoring', title: 'Future Authoring exercise' },
	{ slug: 'attend/gaia', title: 'Gaia' },
	{ slug: 'attend/get-real-biblography', title: 'Biblography' },
	{ slug: 'attend/get-real-definitions', title: 'Definitions for Get Real' },
	{ slug: 'attend/get-real-foreword', title: 'Foreword' },
	{ slug: 'attend/get-real-glossary', title: 'Glossary' },
	{ slug: 'attend/get-real-intro', title: 'Synopsis' },
	{ slug: 'attend/get-real-preface', title: 'Preface' },
	{ slug: 'attend/get-real-synopsis', title: 'Synopsis Of Get Real' },
	{ slug: 'attend/get-real', title: 'Get Real' },
	{
		slug: 'attend/good-guild-jewelry-stories',
		title: 'Good Guild Jewelry Stories',
	},
	{ slug: 'attend/gravity', title: 'gravity' },
	{ slug: 'attend/greater-minds-theory', title: 'Greater Minds Theory' },
	{ slug: 'attend/guilt', title: 'guilt' },
	{ slug: 'attend/gurdjieff', title: 'G.I. Gurdjieff' },
	{ slug: 'attend/gylany', title: 'Gylany' },
	{ slug: 'attend/harmony', title: 'harmony' },
	{ slug: 'attend/heart', title: 'Heart' },
	{ slug: 'attend/hermann-hesse', title: 'Hermann Hesse' },
	{ slug: 'attend/hexagram-a-day', title: 'Hexagram A Day' },
	{ slug: 'attend/hierarchy', title: 'Hierarchy' },
	{ slug: 'attend/how-did-i-get-here', title: 'How Did I Get Here' },
	{ slug: 'attend/how-to-be-sovereign', title: 'How to be Sovereign' },
	{ slug: 'attend/how-to-breed-bliss', title: 'How to Breed Bliss' },
	{
		slug: 'attend/how-to-decide-make-your-own-crystal-ball',
		title: 'How to Decide-Make Your Own Crystal Ball',
	},
	{
		slug: 'attend/how-to-do-philosophy-communally',
		title: 'How to Do Philosophy Communally',
	},
	{ slug: 'attend/how-to-play', title: 'How To Play' },
	{ slug: 'attend/identity-or-sovereignty', title: 'Identity or Sovereignty' },
	{ slug: 'attend/identity', title: 'identity' },
	{
		slug: 'attend/ignorance-is-my-main-drive',
		title: 'ignorance is my main drive',
	},
	{ slug: 'attend/ignorance', title: 'Ignorance' },
	{ slug: 'attend/in-progress', title: 'in-progress' },
	{ slug: 'attend/information', title: 'Information' },
	{ slug: 'attend/insight', title: 'insight' },
	{
		slug: 'attend/integrated-information-theory',
		title: 'Integrated Information Theory',
	},
	{ slug: 'attend/integration', title: 'integration' },
	{ slug: 'attend/intellect', title: 'Intellect' },
	{ slug: 'attend/intelligence', title: 'Intelligence' },
	{ slug: 'attend/intent', title: 'Intent' },
	{ slug: 'attend/intention', title: 'Intention' },
	{ slug: 'attend/intuition', title: 'Intuition' },
	{ slug: 'attend/joe-frank', title: 'Joe Frank' },
	{ slug: 'attend/journal', title: 'A Journal of Kerrbear' },
	{ slug: 'attend/joy', title: 'Joy' },
	{ slug: 'attend/judgment', title: 'Judgment' },
	{ slug: 'attend/juega-party', title: 'Juega Party' },
	{ slug: 'attend/karl-poppers-philosophy', title: "Karl Popper's Philosophy" },
	{ slug: 'attend/karma', title: 'karma' },
	{
		slug: 'attend/kindle-highlight-color-heuristic-mnemonics',
		title: 'Kindle highlight color heuristic mnemonics',
	},
	{ slug: 'attend/knowing', title: 'Knowing' },
	{ slug: 'attend/knowledge', title: 'Knowledge' },
	{ slug: 'attend/language', title: 'language' },
	{ slug: 'attend/law-of-return', title: 'Law of Return' },
	{
		slug: 'attend/life-is-what-you-manifest',
		title: 'Life Is What You Manifest',
	},
	{ slug: 'attend/life', title: 'life' },
	{ slug: 'attend/light', title: 'light' },
	{ slug: 'attend/loins', title: 'loins' },
	{ slug: 'attend/love-is-the-answer', title: 'Love is the Answer' },
	{ slug: 'attend/love-or-fear', title: 'Love or Fear' },
	{ slug: 'attend/love', title: 'Love' },
	{ slug: 'attend/magnetism', title: 'magnetism' },
	{ slug: 'attend/manifesto-2', title: 'Manifesto 2' },
	{ slug: 'attend/manifesto-3', title: 'Manifesto 3' },
	{
		slug: 'attend/manifesto',
		title: 'A Gentle Revolution of Love and Connection',
	},
	{ slug: 'attend/mass', title: 'Mass' },
	{ slug: 'attend/material-scientism', title: 'Material Scientism' },
	{ slug: 'attend/materialism', title: 'Materialism' },
	{ slug: 'attend/mathnawi', title: 'Sufi Wisdom' },
	{ slug: 'attend/matter', title: 'Matter' },
	{ slug: 'attend/may-11th-2018', title: 'May 11th, 2018' },
	{ slug: 'attend/meaning-of-life', title: 'The Meaning of Life' },
	{ slug: 'attend/meaning', title: 'Meaning' },
	{ slug: 'attend/meanings-of-cjk-emoji' },
	{ slug: 'attend/memory-palace', title: 'Memory Palace' },
	{ slug: 'attend/memory', title: 'Memory' },
	{ slug: 'attend/might-it-be-that', title: 'Might it be that' },
	{ slug: 'attend/mind', title: 'Mind' },
	{ slug: 'attend/mindfulness', title: 'mindfulness' },
	{ slug: 'attend/mnemonic', title: 'mnemonic' },
	{ slug: 'attend/mobius-ouroboros', title: 'Möbius Ouroboros' },
	{ slug: 'attend/money', title: 'Money' },
	{ slug: 'attend/moon', title: 'Moon' },
	{ slug: 'attend/morphic-resonance', title: 'Morphic Resonance' },
	{
		slug: 'attend/mutually-defining-opposites',
		title: 'Mutually Defining Opposites',
	},
	{ slug: 'attend/naas-invite', title: 'Naas,Invite' },
	{
		slug: 'attend/naas-moderator-questions',
		title: 'Naas,Moderator,Questions',
	},
	{ slug: 'attend/need', title: 'Need' },
	{ slug: 'attend/neural-networks', title: 'Neural networks' },
	{ slug: 'attend/neuroscience', title: 'Neuroscience' },
	{ slug: 'attend/non-existence', title: 'non-existence' },
	{
		slug: 'attend/non-physical-material-reality',
		title: 'Non Physical Material Reality',
	},
	{ slug: 'attend/nonlocality', title: 'Nonlocality' },
	{ slug: 'attend/noticing-or-imagining', title: 'Noticing or Imagining' },
	{ slug: 'attend/now-reading', title: 'Now Reading' },
	{ slug: 'attend/oe', title: 'Oe' },
	{ slug: 'attend/oneness', title: 'Oneness' },
	{ slug: 'attend/only-every-annotated', title: 'The Origin of Everything' },
	{ slug: 'attend/only-every', title: 'Only Every' },
	{ slug: 'attend/orgasm', title: 'orgasm' },
	{ slug: 'attend/origin', title: 'Origin' },
	{ slug: 'attend/origins', title: 'Origins' },
	{ slug: 'attend/outline-for-get-real', title: 'Outline for Get Real' },
	{ slug: 'attend/pain', title: 'Pain' },
	{ slug: 'attend/panpsychism', title: 'Panpsychism' },
	{ slug: 'attend/pantry-raid', title: 'Pantry Raid' },
	{
		slug: 'attend/paraphrasing-byron-katie',
		title:
			'Paraphrasing Byron Katie and Stephen Mitchell on the Diamond Sutra and The Work',
	},
	{ slug: 'attend/paraphrasing-campbell', title: 'Paraphrasing Tom Campbell' },
	{ slug: 'attend/paraplanes', title: 'Paraplanes' },
	{ slug: 'attend/perception', title: 'Perception' },
	{ slug: 'attend/personality', title: 'personality' },
	{ slug: 'attend/petition', title: 'Petition' },
	{ slug: 'attend/philosophy-glossary', title: 'Philosophy Glossary' },
	{ slug: 'attend/physical-realities', title: 'Physical Realities' },
	{ slug: 'attend/physics', title: 'Physics today - a brief overview' },
	{ slug: 'attend/pink-and-sticky', title: 'Pink and Sticky' },
	{ slug: 'attend/play', title: 'Play' },
	{ slug: 'attend/pleasure', title: 'pleasure' },
	{ slug: 'attend/prana', title: 'prana' },
	{ slug: 'attend/premises-for-get-real', title: 'Premises for Get Real' },
	{ slug: 'attend/premises', title: 'Premises' },
	{ slug: 'attend/prologue', title: 'Prologue' },
	{ slug: 'attend/properties-of-a-mind', title: 'Properties of a Mind' },
	{ slug: 'attend/protein-folding', title: 'Protein Folding' },
	{ slug: 'attend/q&a', title: 'Answers' },
	{ slug: 'attend/qigong', title: 'qigong' },
	{ slug: 'attend/qualia', title: 'Qualia' },
	{ slug: 'attend/quality', title: 'Quality' },
	{ slug: 'attend/quanta', title: 'quanta' },
	{ slug: 'attend/quantity', title: 'Quantity' },
	{ slug: 'attend/quantum-consciousness', title: 'Quantum Consciousness' },
	{
		slug: 'attend/quantum-reality-and-the-illusion-of-material-determinism',
		title: 'Quantum Reality and the Illusion of Material Determinism',
	},
	{ slug: 'attend/quantum', title: 'quantum' },
	{ slug: 'attend/quotes-reading', title: 'Quotes' },
	{ slug: 'attend/randomness', title: 'Randomness' },
	{ slug: 'attend/readiness-potential', title: 'readiness potential' },
	{ slug: 'attend/reading-aeon', title: 'Reading Aeon' },
	{ slug: 'attend/reading-be-as-you-are', title: 'Reading Be As You Are' },
	{ slug: 'attend/reading-eisenstein', title: 'Reading Eisenstein' },
	{ slug: 'attend/reading-emerson', title: 'Reading Emerson' },
	{ slug: 'attend/reading-exhalation', title: 'Reading Exhalation' },
	{ slug: 'attend/reading-ibn-tufayn', title: 'Reading Ibn Tufayn' },
	{ slug: 'attend/reading-ishmael', title: 'Reading Ishmael' },
	{
		slug: 'attend/reading-louise-l-hay-letting-guilt-go',
		title: 'Reading Louise L. Hay',
	},
	{ slug: 'attend/reading-ohsawa', title: 'Reading Ohsawa' },
	{
		slug: 'attend/reading-the-doors-of-perception',
		title: 'The Doors Of Perception',
	},
	{
		slug: 'attend/reading-the-first-forty-days',
		title: 'The First Forty Days',
	},
	{
		slug: 'attend/reading-the-power-of-now',
		title: 'Reading The Power of Now',
	},
	{ slug: 'attend/reading', title: 'Reading' },
	{ slug: 'attend/reality', title: 'Reality' },
	{ slug: 'attend/recapture-the-rapture', title: 'Recapture The Rapture' },
	{ slug: 'attend/recognition', title: 'Recognition' },
	{ slug: 'attend/rejection', title: 'rejection' },
	{ slug: 'attend/relativity', title: 'relativity' },
	{ slug: 'attend/religion', title: 'Religion' },
	{ slug: 'attend/renaming-consciousness', title: 'Renaming Consciousness' },
	{ slug: 'attend/resonance', title: 'Resonance' },
	{ slug: 'attend/resources-for-get-real', title: 'Resources for Get Real' },
	{ slug: 'attend/responsibility', title: 'Responsibility' },
	{ slug: 'attend/roam', title: 'roam' },
	{ slug: 'attend/root-of-all-evil', title: 'root of all evil' },
	{ slug: 'attend/rupert-sheldrake', title: 'Rupert Sheldrake' },
	{ slug: 'attend/samsara', title: 'Samsara' },
	{ slug: 'attend/sapience', title: 'Sapience' },
	{ slug: 'attend/satchitananda', title: 'Satchitananda' },
	{
		slug: 'attend/scientific-dogmas-to-retire',
		title: 'Ten Scientific Dogmas to Retire',
	},
	{
		slug: 'attend/secret-of-the-golden-flower',
		title: 'Secret of the Golden Flower',
	},
	{ slug: 'attend/self-consciousness', title: 'Self-Consciousness' },
	{
		slug: 'attend/self-sovereign-manifesto',
		title: 'Self-Sovereign Manifesto',
	},
	{ slug: 'attend/self', title: 'Self' },
	{ slug: 'attend/sensation', title: 'sensation' },
	{ slug: 'attend/sentience', title: 'Sentience' },
	{ slug: 'attend/separation', title: 'separation' },
	{ slug: 'attend/serendipity', title: 'Serendipity' },
	{
		slug: 'attend/shall-we-advance-proceed-be',
		title: 'Shall We Advance, Proceed, Be?',
	},
	{ slug: 'attend/shame', title: 'shame' },
	{ slug: 'attend/siddhartha', title: 'Siddhartha' },
	{ slug: 'attend/siiwssibd', title: 'Siiwssibd' },
	{
		slug: 'attend/slaughterhouse-five-notes',
		title: 'slaughterhouse five notes',
	},
	{ slug: 'attend/slave-free-economy', title: 'Slave-free Economy' },
	{ slug: 'attend/smile-spots', title: 'Smile Spots' },
	{ slug: 'attend/smilehug', title: 'Smilehug' },
	{ slug: 'attend/source', title: 'Source' },
	{ slug: 'attend/sovereign', title: 'sovereign' },
	{ slug: 'attend/sovereignty', title: 'Sovereignty' },
	{ slug: 'attend/space', title: 'space' },
	{ slug: 'attend/spacetime', title: 'Spacetime' },
	{ slug: 'attend/speed-of-light', title: 'speed-of-light' },
	{ slug: 'attend/state-of-the-unity', title: 'State of the Unity' },
	{ slug: 'attend/steppenwolf', title: 'Steppenwolf' },
	{ slug: 'attend/steve-kaufman', title: 'Steve Kaufman' },
	{
		slug: 'attend/stories/1000-words-from-an-immortal',
		title: "Tuko - A Fate in Sheep's Clotho",
	},
	{
		slug: 'attend/stories/Birdie/birdie-characters',
		title: 'The Characters of Birdie',
	},
	{
		slug: 'attend/stories/Birdie/birdie-research-and-inspirations',
		title: 'Birdie Research',
	},
	{
		slug: 'attend/stories/Birdie/characters/birds',
		title: 'Characters of Birdie',
	},
	{ slug: 'attend/stories/Birdie/characters/man', title: 'Who is this man?' },
	{ slug: 'attend/stories/Birdie/dialogues/seats', title: 'Seats' },
	{ slug: 'attend/stories/Birdie/god', title: 'Does Birdie believe in God?' },
	{
		slug: 'attend/stories/Birdie/inspirations',
		title: 'Inspirations for *Birdie*',
	},
	{ slug: 'attend/stories/Birdie/purpose', title: 'Why am I writing Birdie?' },
	{
		slug: 'attend/stories/Birdie/quotes/philip-k-dick',
		title: 'Philip K Dick',
	},
	{
		slug: 'attend/stories/Birdie/quotes/rebecca',
		title: 'Quotes from Daphne du Maurier',
	},
	{
		slug: 'attend/stories/Birdie/settings/home',
		title: 'Where does the Birdie live',
	},
	{ slug: 'attend/stories/Birdie/she-flies', title: 'she flies' },
	{ slug: 'attend/stories/Birdie/synopses/prime', title: 'Prime' },
	{ slug: 'attend/stories/Birdie/tactics', title: 'How to make Birdie' },
	{ slug: 'attend/stories/arline-the-a-bomb', title: 'Arline was the bomb' },
	{
		slug: 'attend/stories/ascent-of-mt-st-helens',
		title: 'Ascent of Mt. St. Helens',
	},
	{ slug: 'attend/stories/atman/an-oysters-life', title: 'An Oyster Life' },
	{ slug: 'attend/stories/atman/axioms-of-atman', title: 'Axioms of Atman' },
	{
		slug: 'attend/stories/atman/characters-of-atman',
		title: 'Characters of Atman',
	},
	{ slug: 'attend/stories/atman/events-of-atman', title: 'Events of Atman' },
	{
		slug: 'attend/stories/atman/narrative-of-atman',
		title: 'Narrative of Atman',
	},
	{
		slug: 'attend/stories/atman/nomenclature-of-atman',
		title: 'Nomenclature of Atman',
	},
	{
		slug: 'attend/stories/atman/settings-of-atman',
		title: 'Settings of Atman',
	},
	{ slug: 'attend/stories/atman/themes-of-atman', title: 'Themes of Atman' },
	{ slug: 'attend/stories/atman', title: 'Ātman' },
	{
		slug: 'attend/stories/clotho-rewoven',
		title: 'Clotho Rewoven - Confessions of Fate',
	},
	{ slug: 'attend/stories/dr.-malesalsus', title: 'Dr. Malesalsus' },
	{ slug: 'attend/stories/dreamt-of-a-wreck', title: 'Dreamt Of A Wreck' },
	{
		slug: 'attend/stories/friending-3.0---drowning-in-aether',
		title: 'Friending 3.0',
	},
	{
		slug:
			'attend/stories/integratron-a-brief-history-of-giant-rock-covering-the-last-90-years-1887',
		title: 'The Integratron',
	},
	{ slug: 'attend/stories/nativity-redux', title: 'Nativity Redux' },
	{
		slug: 'attend/stories/near-death-experiences',
		title: 'Near Death Experiences - What Almost Killed Me',
	},
	{
		slug: 'attend/stories/nomenclature-of-atman--nomenclature',
		title: 'Nomenclature of Atman | Nomenclature',
	},
	{ slug: 'attend/stories/passport-snafu', title: 'Passport SNAFU' },
	{
		slug: 'attend/stories/playing-title/chapter-1-flying',
		title: 'Playing Title',
	},
	{
		slug: 'attend/stories/playing-title/crafting-a-tale',
		title: 'Crafting a Tale',
	},
	{
		slug:
			'attend/stories/playing-title/in-the-city-we-were-leashed-in-the-country-we-ran-free',
		title: 'In The City We Were Leashed In The Country We Ran Free',
	},
	{
		slug: 'attend/stories/playing-title/rough-outline',
		title: 'Playing Title',
	},
	{ slug: 'attend/stories/rams-bumping-uglily', title: 'Uglily Ramscuttle' },
	{ slug: 'attend/stories/sans-transchizo', title: 'Sans Transchizo' },
	{
		slug: 'attend/stories/sissy-no-fuss/sissy-no-fuss-ep-1',
		title: 'Sissy Nofuss',
	},
	{
		slug: 'attend/stories/sissy-no-fuss/sissy-no-fuss-ep-2',
		title: 'Sissy, No Fuss',
	},
	{ slug: 'attend/stories/squirrels-and-crows', title: 'Squirrels And Crows' },
	{
		slug: 'attend/stories/the-desiccation-conspiracy',
		title: 'The Desiccation Conspiracy',
	},
	{
		slug: 'attend/stories/the-skid-marks-of-buddha',
		title: 'Spotting Sasplotch',
	},
	{
		slug: 'attend/stories/theres-nothing-to-worry-about',
		title: 'Theres Nothing To Worry About',
	},
	{ slug: 'attend/strange-loop', title: 'Strange Loop' },
	{ slug: 'attend/string-theory', title: 'String Theory' },
	{ slug: 'attend/structured-water', title: 'Structured Water' },
	{ slug: 'attend/sustainability', title: 'Sustainability' },
	{ slug: 'attend/tao', title: 'Tao' },
	{ slug: 'attend/tathata', title: 'tathata' },
	{ slug: 'attend/taxonomy-of-the-mind', title: 'Taxonomy of the Mind' },
	{ slug: 'attend/taxonomy', title: 'taxonomy' },
	{ slug: 'attend/telepathic-dogs', title: 'telepathic-dogs' },
	{
		slug: 'attend/tending-toward-a-model-of-consciousness',
		title: 'Tending Toward a Model of Consciousness',
	},
	{ slug: 'attend/the-celestine-prophecy', title: 'The Celestine Prophecy' },
	{
		slug: 'attend/the-consciousness-manifesto',
		title: 'The Consciousness Manifesto',
	},
	{
		slug:
			'attend/the-difference-between-what-we-perceive-and-what-what-really-is',
		title: 'The Difference Between What We Perceive And What What Really Is',
	},
	{ slug: 'attend/the-game-index', title: 'The Game Index' },
	{ slug: 'attend/the-game', title: 'The Game' },
	{
		slug: 'attend/the-hard-problem',
		title: 'The Hard Problem of Neuroscience',
	},
	{ slug: 'attend/the-learning-ladder', title: 'The Learning Ladder' },
	{ slug: 'attend/the-pantheon', title: 'The Pantheon' },
	{
		slug: 'attend/the-pre-socratics--a-survey',
		title: 'The Pre-Socratics - A Survey',
	},
	{
		slug: 'attend/the-principle-of-correspondence',
		title: 'The Principle of Correspondence',
	},
	{ slug: 'attend/the-rules', title: 'The Rules of the Game' },
	{ slug: 'attend/the-science-delusion', title: 'The Science Delusion' },
	{ slug: 'attend/the-speed-of-light', title: 'The Speed of Light' },
	{ slug: 'attend/the-truth', title: 'The Truth' },
	{ slug: 'attend/the-whys-behind-our-is', title: 'The Whys Behind our Is' },
	{ slug: 'attend/theory-of-mind', title: 'Theory of Mind' },
	{ slug: 'attend/theravada', title: 'Theravada' },
	{ slug: 'attend/third-eye', title: 'Third Eye' },
	{ slug: 'attend/time-machines', title: 'Time Machines' },
	{
		slug:
			'attend/time-with-orland-and-charles-and-patsy-eisenstein-and-shavani-marshall',
		title:
			'Time with Orland and Charles and Patsy Eisenstein and Shavani Marshall',
	},
	{ slug: 'attend/time', title: 'On Time' },
	{ slug: 'attend/titles-for-get-real', title: 'Titles for Get Real' },
	{
		slug: 'attend/to-summarize-unified-field-theory',
		title: 'Unified Field Theory',
	},
	{ slug: 'attend/tom-campbell', title: 'Tom Campbell' },
	{ slug: 'attend/topics-of-get-real', title: 'Topics of Get Real' },
	{
		slug: 'attend/traveling-thru-quantized-time',
		title: 'Traveling Thru Quantized Time',
	},
	{ slug: 'attend/truth', title: 'Truth' },
	{
		slug: 'attend/types-of-stupid-umberto-eco',
		title: 'Types of Stupid by Umberto Eco',
	},
	{ slug: 'attend/unbound', title: 'unbound' },
	{ slug: 'attend/understanding', title: 'Understanding' },
	{ slug: 'attend/unified-reality-theory', title: 'Unified Reality Theory' },
	{ slug: 'attend/unity', title: 'unity' },
	{ slug: 'attend/ursula-k-le-guin', title: 'Ursula K. Le Guin' },
	{
		slug: 'attend/usury-is the-fruit-of-all-evil',
		title: 'Usury is the Fruit of All Evil',
	},
	{ slug: 'attend/usury', title: 'usury' },
	{ slug: 'attend/void', title: 'void' },
	{ slug: 'attend/want', title: 'want' },
	{
		slug: 'attend/we-can-do-better-than-this',
		title: 'We Can Do Better Than This',
	},
	{
		slug: 'attend/we-live-to-dance-and-dance-to-live',
		title: 'We live to dance and dance to live',
	},
	{
		slug: 'attend/wealth-redi',
		title: 'Wealth redistribution and class warfare',
	},
	{
		slug: 'attend/what-are-we-scared-to-lose',
		title: 'What are we scared to lose?',
	},
	{ slug: 'attend/what-is-worth-doing', title: 'What Is Worth Doing‽' },
	{ slug: 'attend/what-words-made-us-do', title: 'What Words Made Us (Do)' },
	{ slug: 'attend/where-babies-come-from', title: 'Where Babies Come From' },
	{ slug: 'attend/where-is-my-mind', title: 'Where Is My Mind' },
	{ slug: 'attend/who-am-i', title: 'who am I' },
	{ slug: 'attend/why-am-i-here', title: 'Why Am I Here' },
	{ slug: 'attend/why-do-we-dance', title: 'Why do we dance?' },
	{ slug: 'attend/wisdom', title: 'wisdom' },
	{
		slug: 'attend/wittgenstein-on-mysticism',
		title: 'Wittgenstein on Mysticism',
	},
	{ slug: 'attend/work-search', title: 'Where to Be of Service' },
	{ slug: 'attend/workfree', title: 'Workfree' },
	{ slug: 'attend/yen', title: 'Yen' },
	{ slug: 'attend/yijing', title: 'Yìjīng' },
	{ slug: 'attend/उपेक्षा', title: 'उपेक्षा' },
	{ slug: 'attend/करुणा', title: 'करुणा' },
	{ slug: 'attend/मुदिता', title: 'मुदिता' },
	{ slug: 'attend', title: 'Attend' },
	{ slug: 'forget/100-books-i-adore', title: '100 Books I Adore' },
	{ slug: 'forget/2016-resolutions', title: '2016 Resolutions' },
	{ slug: 'forget/Identity/krry-in-a-nutshell', title: 'Krry in a Nutshell' },
	{ slug: 'forget/Identity/krry-who-am-i', title: 'KRRYME' },
	{
		slug: 'forget/Identity/krrydotme/krry.me-homepage-concept',
		title: 'krry.me Concept',
	},
	{
		slug: 'forget/Identity/krrydotme/krrydotme-back-to-the-drawing-board',
		title: 'krry.me - back to the drawing board',
	},
	{
		slug:
			'forget/Identity/krrydotme/this-silly-place-is-the-result-of-a-labor-of-love-but-really',
		title: 'This Silly Place Is The Result Of A Labor Of Love But Really',
	},
	{
		slug: 'forget/Identity/musings-on-method-vs.-identity',
		title: 'Musings On Method Vs. Identity',
	},
	{ slug: 'forget/Identity/my-will', title: 'My Anonymous Will' },
	{ slug: 'forget/Identity/what-can-krry-do', title: 'What can I do?' },
	{ slug: 'forget/Identity/who-is-krry', title: 'Who is Krry' },
	{
		slug: 'forget/advice-from-a-young-man',
		title: 'Advice from a seemingly young, arguably wise man',
	},
	{ slug: 'forget/an-old-blotter', title: 'An Old Blotter' },
	{
		slug: 'forget/an-open-apology-to-internet-forums-why-i-dont-post',
		title: 'An Open Apology To Internet Forums Why I Dont Post',
	},
	{
		slug: 'forget/an-open-letter-to-wunderkinder-and-reminders',
		title: 'An Open Letter To Wunderkinder And Reminders',
	},
	{ slug: 'forget/apple-sux', title: 'Apple Sux' },
	{ slug: 'forget/atmanautica-portfolio', title: 'Atmanautica Folio' },
	{ slug: 'forget/blockchain-notes', title: 'Blockchain' },
	{
		slug: 'forget/blockchain-web-3+',
		title: 'Web 3.5 - Trust has always been paramount, but absent',
	},
	{ slug: 'forget/brahmavihārās', title: 'Brahmavihārās' },
	{ slug: 'forget/branciforte', title: 'branciforte' },
	{ slug: 'forget/chronology', title: 'Chronology' },
	{ slug: 'forget/citation', title: 'Citation' },
	{ slug: 'forget/coconot', title: 'coconot' },
	{
		slug: 'forget/culture-is-not-your-friend',
		title: 'Culture Is Not Your Friend',
	},
	{ slug: 'forget/dedication', title: 'Dedication' },
	{ slug: 'forget/detachment', title: 'Detachment' },
	{ slug: 'forget/dmt-breakthroughs', title: 'DMT Breakthroughs' },
	{ slug: 'forget/fantasy-homepage-rant', title: 'Fantasy Homepage rant' },
	{ slug: 'forget/fixing-windows', title: 'Fixing Windows' },
	{ slug: 'forget/foreword', title: 'Forewords' },
	{ slug: 'forget/goals', title: 'Goals' },
	{ slug: 'forget/human-senses', title: 'Human Senses' },
	{
		slug: 'forget/ideal-qualities-in-a-modern-woman',
		title: 'Ideal Qualities in a Modern Woman',
	},
	{
		slug: 'forget/journal/2012-11-17-talkers-vs.-doers',
		title: '20121117 Talkers Vs. Doers',
	},
	{ slug: 'forget/journal/2018-04-22', title: 'Journal entry 2018-04-22' },
	{ slug: 'forget/journal/2018-04-24', title: 'Journal entry 2018-04-24' },
	{ slug: 'forget/journal/2018-05-11', title: 20180511 },
	{ slug: 'forget/journal/2019-resolutions', title: '2019-resolutions' },
	{ slug: 'forget/journal/2020-09-04', title: 20200904 },
	{ slug: 'forget/journal/2020-09-06', title: 20200906 },
	{ slug: 'forget/journal/2020-09-09', title: 20200909 },
	{ slug: 'forget/journal/2020-12-26', title: 20201226 },
	{ slug: 'forget/journal/2020-12-27', title: 'Journal 2020 Dec 27' },
	{ slug: 'forget/journal/2020-12-28', title: 20201228 },
	{ slug: 'forget/journal/2020-12-29', title: 20201229 },
	{ slug: 'forget/journal/2020-12-30', title: 20201230 },
	{ slug: 'forget/journal/2020-12-31', title: 20201231 },
	{
		slug: 'forget/journal/2021-01-01',
		title: 'Kerrbear Journal Entry 2020-01-01',
	},
	{ slug: 'forget/journal/2021-01-02', title: 20210102 },
	{ slug: 'forget/journal/2021-01-03', title: 20210103 },
	{ slug: 'forget/journal/2021-01-05', title: 20210105 },
	{ slug: 'forget/journal/2021-01-07', title: 20210107 },
	{ slug: 'forget/journal/2021-01-09', title: 20210109 },
	{ slug: 'forget/journal/2021-01-10', title: 20210110 },
	{ slug: 'forget/journal/2021-01-11', title: 20210111 },
	{ slug: 'forget/journal/2021-01-14', title: 20210114 },
	{ slug: 'forget/journal/2021-01-16', title: 20210116 },
	{ slug: 'forget/journal/2021-01-20', title: 20210120 },
	{ slug: 'forget/journal/2021-01-22', title: 20210122 },
	{ slug: 'forget/journal/2021-01-24', title: 20210124 },
	{ slug: 'forget/journal/2021-02-08', title: 20210208 },
	{ slug: 'forget/journal/2021-02-15', title: 20210215 },
	{ slug: 'forget/journal/2021-02-16', title: 20210216 },
	{ slug: 'forget/journal/2021-02-17', title: 20210217 },
	{ slug: 'forget/journal/2021-02-19', title: 'Journal Entry 2021-02-19' },
	{ slug: 'forget/journal/2021-02-21', title: 20210221 },
	{ slug: 'forget/journal/2021-02-24', title: 20210224 },
	{
		slug: 'forget/journal/2021-02-26',
		title: 'Journal, pandemic fulcrum toward the Great Relax',
	},
	{ slug: 'forget/journal/2021-03-03', title: 'Journal of Kerrbear 20210303' },
	{ slug: 'forget/journal/2021-03-04', title: 'Thursday, March 4, 2021' },
	{
		slug: 'forget/journal/2021-03-05',
		title: 'Journal Entry, Friday, March 05, 2021',
	},
	{
		slug: 'forget/journal/2021-03-06',
		title: 'Journal Entry, Saturday, March 06, 2021',
	},
	{
		slug: 'forget/journal/2021-03-08',
		title: 'Journal Entry, Monday, March 08, 2021',
	},
	{ slug: 'forget/journal/2021-03-13', title: 'Journal Entry 2021 March 13' },
	{ slug: 'forget/journal/2021-03-14', title: 'Kerrbear Journal 2021-03-14' },
	{ slug: 'forget/journal/2021-03-19', title: 'Kerrbear Journal 2021-03-19' },
	{ slug: 'forget/journal/2021-03-20', title: 'Kerrbear Journal 2021-03-20' },
	{ slug: 'forget/journal/2021-03-25-vaccinated', title: 'Vaccinated' },
	{
		slug: 'forget/journal/2021-04-01',
		title: 'Journal of Kerrbear 2021-04-01',
	},
	{
		slug: 'forget/journal/2021-04-02',
		title: 'Journal of Kerrbear 2021-04-02',
	},
	{
		slug: 'forget/journal/2021-04-03',
		title: 'Journal of Kerrbear 2021-04-03',
	},
	{
		slug: 'forget/journal/2021-04-05',
		title: 'Journal of Kerrbear 2021-04-05',
	},
	{
		slug: 'forget/journal/2021-04-11',
		title: 'Journal of Kerrbear 2021-04-11',
	},
	{ slug: 'forget/journal/2021-resolutions', title: '2021 Resolutions' },
	{ slug: 'forget/journal/covision', title: 'Covision' },
	{ slug: 'forget/journal/cumulative-culture', title: 'Cumulative Culture' },
	{ slug: 'forget/journal/enthea-design', title: 'Enthea Design' },
	{ slug: 'forget/journal/entify', title: 'entify' },
	{
		slug: 'forget/journal/herd-immunity-requires-a-hive-mentality',
		title: 'Herd immunity requires a hive mentality',
	},
	{
		slug: 'forget/journal/how-i-can-enjoy-work-again',
		title: 'How I Can Enjoy Work Again',
	},
	{ slug: 'forget/journal/ideatokens', title: 'Ideatokens' },
	{
		slug: 'forget/journal/life-is-occult-to-women-death-is-occult-to-men',
		title: 'life is occult to women, death is occult to men',
	},
	{
		slug: 'forget/journal/pandemics-precede-joyous-periods.',
		title: 'Pandemics precede joyous periods.',
	},
	{ slug: 'forget/journal/resolutions', title: 'resolutions' },
	{
		slug: 'forget/memoirs/a-timely-pretirement',
		title: 'A Timely Pretirement',
	},
	{
		slug: 'forget/memoirs/drowning-is-easy',
		title: 'How to drown yourself and live to write about it',
	},
	{
		slug:
			'forget/memoirs/i-am-a-son-of-the-united-states-of-america-vintage-1982',
		title: 'Memories of HFS',
	},
	{ slug: 'forget/memoirs/jungle-juice', title: 'Jungle Juicy' },
	{
		slug: 'forget/memoirs/memoirs-of-the-holy-family-ep.-1',
		title: 'Memoirs Of The Holy Family Ep. 1',
	},
	{
		slug: 'forget/memoirs/reexamining-my-purpose',
		title: 'Reexamining my purpose',
	},
	{ slug: 'forget/my-best-year', title: 'A year in a cave, day by day' },
	{ slug: 'forget/naming-blotter', title: 'Naming Blotter' },
	{ slug: 'forget/naming-my-aroma', title: 'naming my aroma' },
	{
		slug: 'forget/notebooks/field-notes-template',
		title: 'Field Notes Template',
	},
	{ slug: 'forget/notebooks/field-notes', title: 'Field Notes' },
	{ slug: 'forget/notebooks/fn01', title: 'Fn01' },
	{ slug: 'forget/notebooks/fn02', title: 'Fn02' },
	{ slug: 'forget/notebooks/fn03', title: 'Fn03' },
	{ slug: 'forget/notebooks/fn04', title: 'Fn04' },
	{ slug: 'forget/notebooks/fn05', title: 'Fn05' },
	{ slug: 'forget/notebooks/fn06', title: 'Fn06' },
	{ slug: 'forget/notebooks/fn07', title: 'Fn07' },
	{ slug: 'forget/notebooks/fn08', title: 'Fn08' },
	{ slug: 'forget/notebooks/fn09', title: 'Fn09' },
	{ slug: 'forget/notebooks/fn10', title: 'Fn10' },
	{ slug: 'forget/phonemes-fo-names', title: 'phonemes fo names' },
	{ slug: 'forget/pinch-me-zoom-out', title: 'Pinch me, zoom out' },
	{ slug: 'forget/poems', title: 'Poems' },
	{
		slug: 'forget/poetry/a-matrimonial-blessing-for-dustin-and-ashley',
		title: 'a matrimonial blessing for dustin and ashley',
	},
	{ slug: 'forget/poetry/bemused/1-09-mixed-signal', title: 'Mixed signals' },
	{ slug: 'forget/poetry/bemused/2-c-b-ing', title: '2 C B ing' },
	{
		slug: 'forget/poetry/bemused/a-brief-history-of-life-as-it-was',
		title: 'A Brief History of Life as It Was and Is',
	},
	{
		slug: 'forget/poetry/bemused/a-modest-proposal',
		title: 'A Modest Proposal',
	},
	{
		slug: 'forget/poetry/bemused/a-poem-lets-you-read-in',
		title: 'A Poem Lets You Read In',
	},
	{ slug: 'forget/poetry/bemused/a-tongue-weigher', title: 'A Tongue Weigher' },
	{
		slug: 'forget/poetry/bemused/algebra-for-lovers',
		title: 'Algebra for lovers',
	},
	{ slug: 'forget/poetry/bemused/alit-in-paris', title: 'Alit in Paris' },
	{
		slug: 'forget/poetry/bemused/baby-catcow-blues-at-dawn',
		title: 'Baby Catcow Blues at Dawn',
	},
	{ slug: 'forget/poetry/bemused/bleach-cairn', title: 'Bleach Cairn' },
	{ slug: 'forget/poetry/bemused/bruce-is-art', title: 'Bruce is Art' },
	{ slug: 'forget/poetry/bemused/cosmoji', title: 'Cosmoji' },
	{ slug: 'forget/poetry/bemused/dreamliner', title: 'Dreamliner' },
	{ slug: 'forget/poetry/bemused/drenched', title: 'Drenched' },
	{ slug: 'forget/poetry/bemused/flutterby', title: 'Flutterby' },
	{ slug: 'forget/poetry/bemused/foolsherd', title: 'Foolsherd' },
	{ slug: 'forget/poetry/bemused/four-easy-steps', title: 'Four Easy Steps' },
	{ slug: 'forget/poetry/bemused/free-bird', title: 'Free Bird' },
	{ slug: 'forget/poetry/bemused/giddy-up', title: 'Giddy Up' },
	{
		slug: 'forget/poetry/bemused/give-it-up-horse',
		title: 'Give It Up, Horse',
	},
	{ slug: 'forget/poetry/bemused/godfinger', title: 'Godfinger' },
	{
		slug: 'forget/poetry/bemused/good-score-runnerman',
		title: "Grandma Cecilia's Sports Banter",
	},
	{
		slug: 'forget/poetry/bemused/here-it-is-in-a-nutshell',
		title: 'Here It Is In A Nutshell',
	},
	{
		slug: 'forget/poetry/bemused/how-becoming',
		title: 'We are being experiencing becoming itself',
	},
	{ slug: 'forget/poetry/bemused/hug-the-storm', title: 'Hug the Storm' },
	{
		slug:
			'forget/poetry/bemused/i-keep-thinking-that-this-is-the-beginning-of-something',
		title: 'I Keep Thinking That This Is The Beginning Of Something',
	},
	{ slug: 'forget/poetry/bemused/its-impothable', title: 'Sundrown' },
	{ slug: 'forget/poetry/bemused/lasermothfeels', title: 'Lasermothfeels' },
	{ slug: 'forget/poetry/bemused/magic-mantras', title: 'Magic mantras' },
	{ slug: 'forget/poetry/bemused/make-me-to-feel-2', title: 'Make me to feel' },
	{ slug: 'forget/poetry/bemused/on-your-marks', title: 'On your marks' },
	{
		slug: 'forget/poetry/bemused/one-day-i-want-this-kind-of-time',
		title: 'One day I want this kind of time',
	},
	{ slug: 'forget/poetry/bemused/out-to-pasture-2', title: 'Out to Pasture' },
	{ slug: 'forget/poetry/bemused/painful-airplane', title: 'Painful Airplane' },
	{
		slug: 'forget/poetry/bemused/pantheon-of-swoon',
		title: 'Pantheon of Swoon',
	},
	{ slug: 'forget/poetry/bemused/retrofuture', title: 'Retrofuture' },
	{ slug: 'forget/poetry/bemused/right-at-home', title: 'Right at Home' },
	{ slug: 'forget/poetry/bemused/rise-and-shine', title: 'Rise and Shine' },
	{ slug: 'forget/poetry/bemused/root', title: 'root' },
	{ slug: 'forget/poetry/bemused/same-cannot-be', title: 'Same Cannot Be' },
	{ slug: 'forget/poetry/bemused/sank', title: 'Sank' },
	{
		slug: 'forget/poetry/bemused/so-theres-this-taco-truck',
		title: 'So Theres This Taco Truck',
	},
	{ slug: 'forget/poetry/bemused/sonnet-1', title: 'Sonnet' },
	{ slug: 'forget/poetry/bemused/sonnet-2', title: 'Sonnet 2' },
	{ slug: 'forget/poetry/bemused/this-is-it-tree', title: 'this is it' },
	{ slug: 'forget/poetry/bemused/to-see-being', title: 'To See Being' },
	{ slug: 'forget/poetry/bemused/triple-cream', title: 'Where to begin' },
	{ slug: 'forget/poetry/bemused/unders-redux', title: 'Unders' },
	{ slug: 'forget/poetry/bemused/unders', title: 'Unders' },
	{ slug: 'forget/poetry/bemused/unlicensed-poet', title: 'unlicensed poet' },
	{ slug: 'forget/poetry/bemused/untitled-piece', title: 'Untitled piece' },
	{ slug: 'forget/poetry/bemused/unwind', title: 'Unwind' },
	{ slug: 'forget/poetry/bemused/utopiapocalypse', title: 'Utopiapocalypse' },
	{ slug: 'forget/poetry/bemused/yes-chef', title: 'Yes Chef' },
	{ slug: 'forget/poetry/blessing-gaia', title: 'Blessing Gaia' },
	{
		slug: 'forget/poetry/coyotes-run-these-streets',
		title: 'coyotes run these streets',
	},
	{ slug: 'forget/poetry/curbers', title: 'curbers' },
	{ slug: 'forget/poetry/deuterostome', title: 'deuterostome' },
	{
		slug: 'forget/poetry/ding-dong-the-dream-is-dead',
		title: 'Ding Dong the Dream is Dead',
	},
	{ slug: 'forget/poetry/fart-patio/alanysis', title: 'Alanysis' },
	{ slug: 'forget/poetry/fart-patio/beltwar', title: 'Eclipsing Binaries' },
	{
		slug: 'forget/poetry/fart-patio/betty-rides-again',
		title: 'Betty Rides Again',
	},
	{
		slug: 'forget/poetry/fart-patio/bubby-wubby-cubby',
		title: 'Bubby Wubby Cubby',
	},
	{ slug: 'forget/poetry/fart-patio/catsup', title: 'Gigwig' },
	{ slug: 'forget/poetry/fart-patio/christies', title: 'Christies' },
	{ slug: 'forget/poetry/fart-patio/curtis', title: 'Too Curt' },
	{
		slug: 'forget/poetry/fart-patio/cut-me-up',
		title: "Cut Me Up (I Love Y'all the More)",
	},
	{ slug: 'forget/poetry/fart-patio/dolo', title: 'Dolo-a-gogo' },
	{
		slug: 'forget/poetry/fart-patio/feels-like-tomorrow-today',
		title: 'feels like tomorrow today',
	},
	{
		slug: 'forget/poetry/fart-patio/glitch-on-to-me',
		title: 'Glitch On To Me',
	},
	{
		slug: 'forget/poetry/fart-patio/halloween-is-the-only-day',
		title: 'Halloween Is The Only Day',
	},
	{
		slug: 'forget/poetry/fart-patio/healing-is-every-step',
		title: 'healing is every step',
	},
	{
		slug: 'forget/poetry/fart-patio/listen-to-your-dog',
		title: 'Listen to your dog',
	},
	{ slug: 'forget/poetry/fart-patio/love-poem', title: 'Love Poem' },
	{ slug: 'forget/poetry/fart-patio/part-nah', title: 'Part nah' },
	{
		slug: 'forget/poetry/fart-patio/skirt-around-it',
		title: 'Skirt Around It',
	},
	{ slug: 'forget/poetry/fart-patio/sugar-grin', title: 'Sugar Grin' },
	{ slug: 'forget/poetry/fart-patio/tom-swifties', title: 'Tom Swifties' },
	{
		slug: 'forget/poetry/fart-patio/unscrew-the-stars',
		title: 'Unscrew the stars',
	},
	{
		slug: 'forget/poetry/fart-patio/where-did-prose-get-us',
		title: 'Where Did Prose Get Us',
	},
	{
		slug:
			'forget/poetry/fart-patio/woke-up-next-to-a-sweet-asp-they-were-out-of-the-savory-ones-gotta-st',
		title: 'Woke Up Next To A Sweet Asp',
	},
	{ slug: 'forget/poetry/flavors', title: 'Flavors' },
	{
		slug: 'forget/poetry/galaxy-class-tire-fire',
		title: 'galaxy class tire fire',
	},
	{ slug: 'forget/poetry/hurding', title: 'Hurding' },
	{
		slug: 'forget/poetry/i-change/i-ching-cauldron-poem',
		title: 'Chefneek 18',
	},
	{
		slug: 'forget/poetry/i-change/i-ching-yarrow-stalks',
		title: 'I Ching Yarrow Stalks',
	},
	{
		slug: 'forget/poetry/i-woke-up-today-hoping',
		title: 'I woke up today hoping',
	},
	{
		slug: 'forget/poetry/ive-been-homeless-and-less',
		title: 'Homeless and Less',
	},
	{ slug: 'forget/poetry/oldies/baitin', title: 'Baitin' },
	{ slug: 'forget/poetry/oldies/black-magic', title: 'Black Magic' },
	{
		slug: 'forget/poetry/oldies/cantankerous-contusion',
		title: 'Cantankerous Contusion',
	},
	{
		slug: 'forget/poetry/oldies/chicken-a-la-king',
		title: 'Chicken A La King',
	},
	{ slug: 'forget/poetry/oldies/faithless', title: 'Faithless' },
	{ slug: 'forget/poetry/oldies/head-phones', title: 'Head Phones' },
	{ slug: 'forget/poetry/oldies/newt-poops', title: 'Newt Poops' },
	{ slug: 'forget/poetry/oldies/nothing-to-say', title: 'Nothing To Say' },
	{ slug: 'forget/poetry/oldies/one-last-kiss', title: 'One Last Kiss' },
	{
		slug: 'forget/poetry/oldies/pickle-purse-diversion',
		title: 'Pickle Purse Diversion',
	},
	{ slug: 'forget/poetry/oldies/shes-leaving', title: 'Shes Leaving' },
	{ slug: 'forget/poetry/oldies/troll-rhymes', title: 'Troll Rhymes' },
	{ slug: 'forget/poetry/oldies/verse-workbook', title: 'Verse Workbook' },
	{ slug: 'forget/poetry/oldies/where-you-belong', title: 'Where You Belong' },
	{ slug: 'forget/poetry/oldies/you-can-feel-me', title: 'You Can Feel Me' },
	{ slug: 'forget/poetry/organ-eyes', title: 'Organ Eyes' },
	{ slug: 'forget/poetry/peel-your-baby-blues', title: 'peel your baby blues' },
	{ slug: 'forget/poetry/poems-from-notebooks', title: 'Poems From Notebooks' },
	{
		slug: 'forget/poetry/poverty-is-wanting-more',
		title: 'Poverty Is Wanting More',
	},
	{ slug: 'forget/poetry/scanner-darkly', title: 'Scanner Darkly' },
	{ slug: 'forget/poetry/scraps/000', title: 0 },
	{
		slug: 'forget/poetry/scraps/a-sangam-for-forrest-gander',
		title: 'tourrettes',
	},
	{ slug: 'forget/poetry/scraps/a-touche-toupee', title: 'A Touche Toupee' },
	{
		slug: 'forget/poetry/scraps/age-cavitates-grief',
		title: 'Age Cavitates Grief',
	},
	{ slug: 'forget/poetry/scraps/awetism', title: 'awetism' },
	{
		slug: 'forget/poetry/scraps/betty-rides-again',
		title: 'Betty Rides Again',
	},
	{
		slug: 'forget/poetry/scraps/broomstabbed-ceilings',
		title: 'Broomstabbed Ceilings',
	},
	{ slug: 'forget/poetry/scraps/career-story', title: 'Career Story' },
	{ slug: 'forget/poetry/scraps/day-32', title: 'Day 32' },
	{
		slug: 'forget/poetry/scraps/do-you-circumcise-your-american-spirits',
		title: 'Do You Circumcise Your American Spirits',
	},
	{ slug: 'forget/poetry/scraps/feeling-high', title: 'Feeling high' },
	{ slug: 'forget/poetry/scraps/fruit', title: 'Fruit' },
	{ slug: 'forget/poetry/scraps/grateful-at-last', title: 'Grateful at Last' },
	{
		slug: 'forget/poetry/scraps/green-the-red-parts',
		title: 'Green The Red Parts',
	},
	{ slug: 'forget/poetry/scraps/grew-of', title: 'Grew of' },
	{ slug: 'forget/poetry/scraps/haikus', title: 'Haikus' },
	{ slug: 'forget/poetry/scraps/hard-questions', title: 'hard questions' },
	{ slug: 'forget/poetry/scraps/here-too', title: 'Here too' },
	{ slug: 'forget/poetry/scraps/i-am-somebody', title: 'I Am Somebody' },
	{
		slug: 'forget/poetry/scraps/its-not-a-relief-when-you-wake-up',
		title: 'Its Not A Relief When You Wake Up',
	},
	{ slug: 'forget/poetry/scraps/let-it-lie', title: 'Let it lie' },
	{ slug: 'forget/poetry/scraps/let-now', title: 'Let Now' },
	{ slug: 'forget/poetry/scraps/monks-todo', title: 'Monks Todo' },
	{ slug: 'forget/poetry/scraps/peom', title: 'peom' },
	{ slug: 'forget/poetry/scraps/poem-blotter', title: 'Poetry blotter' },
	{ slug: 'forget/poetry/scraps/quagmire', title: 'Quagmire' },
	{ slug: 'forget/poetry/scraps/sapnu-puas', title: 'Sapnu Puas' },
	{ slug: 'forget/poetry/scraps/sonnet-3', title: 'sonnet 3' },
	{ slug: 'forget/poetry/scraps/splintered', title: 'Splintered' },
	{
		slug: 'forget/poetry/scraps/tail-lights-be-gone',
		title: 'Tail Lights Be Gone',
	},
	{
		slug: 'forget/poetry/scraps/tenderness-beneath-your-honesty',
		title: 'Tenderness Beneath Your Honesty',
	},
	{ slug: 'forget/poetry/scraps/thanksgiving-2018', title: 'Tempest Ride' },
	{
		slug: 'forget/poetry/scraps/the-dirt-doesnt-hold-us',
		title: 'The Dirt Doesnt Hold Us',
	},
	{
		slug: 'forget/poetry/scraps/the-full-moon-has-struck',
		title: 'The Full Moon Has Struck',
	},
	{ slug: 'forget/poetry/scraps/trite-line', title: 'Trite Line' },
	{ slug: 'forget/poetry/scraps/warm-like-harm', title: 'Warm like harm' },
	{
		slug: 'forget/poetry/scraps/waves-catch-particles',
		title: 'Waves? Catch particles.',
	},
	{ slug: 'forget/poetry/scraps/you-see', title: 'You See' },
	{ slug: 'forget/poetry/selfish', title: 'Selfish' },
	{ slug: 'forget/poetry/shortest-path', title: 'Shortest Path' },
	{
		slug: 'forget/poetry/smut/an-ode-to-partisans',
		title: 'An Ode to Partisans',
	},
	{ slug: 'forget/poetry/smut/anyone-got-a-cork', title: 'Anyone Got A Cork' },
	{ slug: 'forget/poetry/smut/explosacrum', title: 'Explosacrum' },
	{ slug: 'forget/poetry/smut/insides', title: 'Insides' },
	{
		slug: 'forget/poetry/smut/it-tears-me-up-by-cecilia',
		title: 'It Tears Me Up',
	},
	{ slug: 'forget/poetry/smut/it-tears-me-up', title: 'It Tears Me Up' },
	{
		slug: 'forget/poetry/storypoems/an-ode-to-solarcity',
		title: 'An Ode To Solarcity',
	},
	{ slug: 'forget/poetry/storypoems/bettybye', title: 'Betty Bye' },
	{ slug: 'forget/poetry/storypoems/christies', title: 'Christies' },
	{
		slug: 'forget/poetry/storypoems/for-ever-and-all-ways',
		title: 'For ever and all ways',
	},
	{ slug: 'forget/poetry/storypoems/fromagex3', title: 'ÆTHER launch' },
	{ slug: 'forget/poetry/storypoems/galeen-whale', title: 'Galeen Whale' },
	{ slug: 'forget/poetry/storypoems/hope-in-swoon', title: 'Hope in Swoon' },
	{
		slug: 'forget/poetry/storypoems/may-the-roads-unto',
		title: 'For Wilds Xmas 2019',
	},
	{
		slug: 'forget/poetry/storypoems/merci-bon-fromagers',
		title: 'Merci Bon Fromagers',
	},
	{
		slug: 'forget/poetry/storypoems/rissa-showed-up',
		title: 'Rissa showed up',
	},
	{ slug: 'forget/poetry/storypoems/tamarind-2', title: 'An Ode to Tamarind' },
	{ slug: 'forget/poetry/storypoems/yes-chef', title: 'Yes Chef' },
	{
		slug: 'forget/poetry/stourmy-do-oh/1-01-always-on-2nd-street',
		title: 'Always on 2nd Street',
	},
	{
		slug: 'forget/poetry/stourmy-do-oh/1-02-time-is-the-currency',
		title: 'Time is the currency',
	},
	{
		slug: 'forget/poetry/stourmy-do-oh/1-03-harmful-beast',
		title: 'Harmful Beast',
	},
	{
		slug: 'forget/poetry/stourmy-do-oh/1-04-i-have-no-melody',
		title: 'I have no melody',
	},
	{
		slug: 'forget/poetry/stourmy-do-oh/1-05-talk-it-out',
		title: 'Talk it out',
	},
	{
		slug: 'forget/poetry/stourmy-do-oh/1-06-battles-resolve',
		title: 'Battles Resolve',
	},
	{ slug: 'forget/poetry/stourmy-do-oh/1-07-balpha', title: 'Balpha' },
	{
		slug: 'forget/poetry/stourmy-do-oh/1-08-against-the-grain',
		title: 'Against the grain',
	},
	{
		slug: 'forget/poetry/stourmy-do-oh/1-10-it-turns-out-you-pass',
		title: 'It turns out you pass',
	},
	{
		slug: 'forget/poetry/stourmy-do-oh/1-11-rhone-meets-rhine',
		title: 'Track 11',
	},
	{
		slug: 'forget/poetry/stourmy-do-oh/2-01-apologies-for-the-hour',
		title: 'Sorry Tribe, I Care',
	},
	{
		slug: 'forget/poetry/stourmy-do-oh/2-02-were-on-the-other-side',
		title: "We're on the other side",
	},
	{ slug: 'forget/poetry/stourmy-do-oh/beast-of-harm', title: 'Beast of Harm' },
	{ slug: 'forget/poetry/stourmy-do-oh/calling-out', title: 'Calling out' },
	{ slug: 'forget/poetry/stourmy-do-oh/fuckwell-1', title: 'Fuckwell' },
	{ slug: 'forget/poetry/stourmy-do-oh/fuckwell-2', title: 'FUCKWELL 2' },
	{ slug: 'forget/poetry/stourmy-do-oh/fuckwell-3', title: 'FUCKWELL 3' },
	{ slug: 'forget/poetry/stourmy-do-oh/fuckwell-4', title: 'FUCKWELL 4' },
	{ slug: 'forget/poetry/stourmy-do-oh/fuximulatioin', title: 'Fuximulation' },
	{
		slug: 'forget/poetry/stourmy-do-oh/make-me-to-feel',
		title: 'Make me to feel',
	},
	{
		slug: 'forget/poetry/stourmy-do-oh/many-poems-start-with-a-cliff',
		title: 'Many Poems Start With A Cliff',
	},
	{ slug: 'forget/poetry/stourmy-do-oh/null-set', title: 'NULLSET' },
	{ slug: 'forget/poetry/stourmy-do-oh/only', title: 'only' },
	{ slug: 'forget/poetry/stourmy-do-oh/plastic-wrap', title: 'Plastic Wrap' },
	{
		slug: 'forget/poetry/stourmy-do-oh/scrub-vs.-princess',
		title: 'Scrub vs. Princess',
	},
	{
		slug: 'forget/poetry/stourmy-do-oh/the-power-of-no',
		title: 'The power of no',
	},
	{
		slug: 'forget/poetry/stourmy-do-oh/yeah-you-could-just-not-be-shitty-also',
		title: 'Yeah You Could Just Not Be Shitty Also',
	},
	{ slug: 'forget/poetry/the-otter-path/ariel', title: 'Ariel' },
	{
		slug: 'forget/poetry/the-otter-path/as-illusions-of-self',
		title: 'As Illusions Of Self',
	},
	{ slug: 'forget/poetry/the-otter-path/elysa-<==>-kerry', title: 'Blip Blop' },
	{ slug: 'forget/poetry/the-otter-path/f-it', title: 'F it' },
	{
		slug: 'forget/poetry/the-otter-path/i-like-yr-nope',
		title: 'I like yr nope',
	},
	{
		slug: 'forget/poetry/the-otter-path/let-the-wave-crash-over-us',
		title: 'Let the wave crash over us 🌊',
	},
	{
		slug:
			'forget/poetry/the-otter-path/my-creative-practice-focuses-on-transformative-design-at-the-interse',
		title:
			'My Creative Practice Focuses On Transformative Design At The Interse',
	},
	{
		slug: 'forget/poetry/the-otter-path/our-space-is-safe',
		title: 'Our Space Is Safe',
	},
	{ slug: 'forget/poetry/the-otter-path/pargnart', title: 'Preganant!' },
	{
		slug: 'forget/poetry/the-otter-path/paul-selig-to-elysa',
		title: 'Paul Selig To Elysa',
	},
	{
		slug: 'forget/poetry/the-otter-path/preseedling-questions',
		title: 'Preseedling Questions',
	},
	{
		slug: 'forget/poetry/the-otter-path/textpoems-to-elysa',
		title: 'Textpoems to Elysa',
	},
	{
		slug: 'forget/poetry/the-otter-path/triggered-isnt-a-feeling',
		title: "Triggered isn't a feeling",
	},
	{ slug: 'forget/poetry/the-otter-path/we-forget', title: 'Cosmic Jokester' },
	{
		slug: 'forget/poetry/the-otter-path/welcome-to-kerrbear',
		title: 'Welcome to Kerrbear',
	},
	{
		slug: 'forget/poetry/the-otter-path/wolftree-wagon',
		title: 'Wolftree Wagon',
	},
	{ slug: 'forget/poetry/to-revise/boo-bam', title: 'Boobam' },
	{ slug: 'forget/poetry/to-revise/dolo-2', title: 'Dolo 2' },
	{ slug: 'forget/poetry/to-revise/dos-love-poem', title: 'Dos Love Poem' },
	{ slug: 'forget/poetry/to-revise/double-vision', title: 'Double Vision' },
	{
		slug: 'forget/poetry/to-revise/litany-against-fear-redux',
		title: 'No Fear',
	},
	{
		slug: 'forget/poetry/to-revise/make-mother-happy',
		title: 'Make mother happy',
	},
	{
		slug: 'forget/poetry/to-revise/make-space-waste-time',
		title: 'Make space + waste time => find yrself',
	},
	{
		slug: 'forget/poetry/to-revise/objectivity-in-the-wakeplace',
		title: 'Objectivity in the Wakeplace',
	},
	{ slug: 'forget/poetry/to-revise/safe-with-me', title: 'Safe With Me' },
	{ slug: 'forget/poetry/to-revise/what-fear-left', title: "Let's face it." },
	{
		slug: 'forget/poetry/to-revise/what-lies-inside',
		title: 'What Lies Inside',
	},
	{ slug: 'forget/poetry/to-revise/wooman', title: 'Wooman' },
	{ slug: 'forget/poetry/zine', title: 'Zine' },
	{ slug: 'forget/poetry', title: 'Poetry' },
	{ slug: 'forget/purpose', title: 'Purpose' },
	{ slug: 'forget/questions', title: 'Questions' },
	{ slug: 'forget/quotes/on-art', title: 'On Art' },
	{ slug: 'forget/quotes/potent-quotables', title: 'Potent Quotables' },
	{ slug: 'forget/quotes/quotes-on-design', title: 'Quotes About Design' },
	{ slug: 'forget/quotes/quotes', title: 'Wayward Quotes' },
	{ slug: 'forget/quotes/tony-hsieh-quote', title: 'How to be' },
	{ slug: 'forget/ram-dass', title: 'Ram Dass' },
	{
		slug: 'forget/retrofuturist-illustrators',
		title: 'Retrofuturist Illustrators',
	},
	{ slug: 'forget/sanity', title: 'Sanity' },
	{ slug: 'forget/scopaethesia', title: 'Scopaethesia' },
	{ slug: 'forget/sectors-id-support', title: 'Sectors Id Support' },
	{ slug: 'forget/sole-call', title: 'Sole Call' },
	{ slug: 'forget/spiritual-energy', title: 'Spiritual Energy' },
	{ slug: 'forget/states-to-visit', title: "States I haven't been to" },
	{ slug: 'forget/suicide', title: 'Suicide' },
	{ slug: 'forget/the-flutterby-exemption', title: 'The Flutterby Exemption' },
	{
		slug: 'forget/the-many-steps-of-setting-up-and-hosting-your-own-ghost-blog',
		title: 'The many steps of setting up and hosting your own ghost blog',
	},
	{ slug: 'forget/theories', title: 'Theories' },
	{ slug: 'forget/thoughts-on-tville', title: 'Thoughts On Tville' },
	{ slug: 'forget/travel-essentials', title: 'Essentials for your travels' },
	{ slug: 'forget/trunk', title: 'Trunk' },
	{ slug: 'forget/tville-idea-depot', title: 'Tville Idea Depot' },
	{
		slug: 'forget/who-inspires-you-the-most',
		title: 'Who inspires you the most?',
	},
	{ slug: 'forget/æ-strategies-2015', title: 'Æ Strategies 2015' },
	{ slug: 'forget/मैत्री', title: 'मैत्री' },
	{ slug: 'forget', title: 'Forget' },
	{ slug: 'intend/1-the-spire-sitter-appears', title: '1. A Spire Shadow' },
	{ slug: 'intend/2-earth', title: '2 Earth, Hexagram Intensive' },
	{ slug: 'intend/2-wet-blanket-welders', title: '2 Wet Blanket Welders' },
	{
		slug: 'intend/Concepts/aether/aether-a-manifesto',
		title: 'AETHER, a manifesto',
	},
	{ slug: 'intend/Concepts/aether/ledmob', title: 'LEDmob' },
	{ slug: 'intend/Concepts/aether/market-players', title: 'Market Players' },
	{
		slug: 'intend/Concepts/aether/turnt---wearable-passive-ar-platform',
		title: 'TURNT',
	},
	{ slug: 'intend/Concepts/aether/turnt', title: 'TURNT' },
	{ slug: 'intend/Concepts/aether/wear-aether', title: 'æsh' },
	{ slug: 'intend/Concepts/aether/æther-origins', title: 'Starting Æther' },
	{ slug: 'intend/Concepts/babysteps', title: 'Babysteps' },
	{ slug: 'intend/Concepts/boop-feels-bot', title: 'Boop' },
	{ slug: 'intend/Concepts/buenomap', title: 'Buenomap' },
	{
		slug: 'intend/Concepts/burning-man-contributions',
		title: 'Burning Man Contributions',
	},
	{ slug: 'intend/Concepts/church-the-game', title: 'Church - The Game' },
	{ slug: 'intend/Concepts/cuppa/cafe-jemima', title: 'Cafe Angiemima' },
	{ slug: 'intend/Concepts/cuppa/cuppa-concept', title: 'Cuppa' },
	{ slug: 'intend/Concepts/cuppa/cuppa-lore', title: 'Cuppa Lore' },
	{ slug: 'intend/Concepts/cuppa/names', title: 'Names' },
	{ slug: 'intend/Concepts/didit---the-have-done-app', title: 'Didit' },
	{ slug: 'intend/Concepts/dryr.nu', title: 'Dryrun' },
	{ slug: 'intend/Concepts/feelswall', title: 'feelswall' },
	{ slug: 'intend/Concepts/forest-an-organic-social-network', title: 'Forest' },
	{
		slug: 'intend/Concepts/genre-tracker',
		title: 'How to keep track of future tracks',
	},
	{ slug: 'intend/Concepts/gumshoe', title: 'Gumshoe' },
	{ slug: 'intend/Concepts/human-api-spec', title: 'Human API Spec' },
	{
		slug: 'intend/Concepts/hyperbole-a-museum-for-everyone',
		title: 'Hyperbole - a museum for everyone',
	},
	{ slug: 'intend/Concepts/innovation-in-2019', title: 'Innovation in 2019' },
	{
		slug: 'intend/Concepts/inventions-to-flesh-out',
		title: 'Inventions to flesh out',
	},
	{ slug: 'intend/Concepts/juego-party', title: 'Juego Party' },
	{ slug: 'intend/Concepts/marketing-in-2016', title: 'Marketing in 2016' },
	{ slug: 'intend/Concepts/movietix', title: 'The True Box Office Champion' },
	{ slug: 'intend/Concepts/pagetop-typewriter', title: 'Pagetop Typewriter' },
	{
		slug: 'intend/Concepts/person-reaction-interest-matrix',
		title: 'Person Reaction Interest Matrix',
	},
	{ slug: 'intend/Concepts/recipes/aji-de-gallina', title: 'Aji De Gallina' },
	{
		slug: 'intend/Concepts/recipes/caldo-verde-especial',
		title: 'Caldo Verde Especial',
	},
	{
		slug: 'intend/Concepts/recipes/magic-potion-no-222',
		title: 'Magic Potion No. 222',
	},
	{
		slug: 'intend/Concepts/recipes/magic-potion-no-33',
		title: 'Magic Potion No. 33',
	},
	{ slug: 'intend/Concepts/souvenir-contact-map-concept', title: 'souvenir' },
	{ slug: 'intend/Concepts/tdbt-app-idea', title: 'Tdbt App' },
	{ slug: 'intend/Concepts/tet-game-for-leo', title: 'Leo Turns Four' },
	{
		slug: 'intend/Concepts/the-butter-postulate',
		title: 'The Butter Postulate',
	},
	{ slug: 'intend/Concepts/toggletown', title: 'Toggletown' },
	{ slug: 'intend/Concepts/tora-development-roadmap', title: 'Tora' },
	{ slug: 'intend/Concepts/trumpst', title: 'Trumpst' },
	{ slug: 'intend/Concepts/usps-becomes-post', title: 'Usps Becomes Post' },
	{
		slug: 'intend/Concepts/visualizing-facebooks-friend-suggestions',
		title: "Visualizing Facebook's friend suggestions",
	},
	{ slug: 'intend/Concepts/vouch4', title: 'Vouch4' },
	{ slug: 'intend/Concepts/wayin', title: 'Wayin' },
	{
		slug: 'intend/Concepts/web-redux/internet-redux',
		title: 'What would the Internet comprise if we invented it today?',
	},
	{ slug: 'intend/Concepts/web-redux/web4-concept', title: 'Web4 Concept' },
	{ slug: 'intend/Concepts/witme-by-eres-gabay', title: 'Witme' },
	{ slug: 'intend/Concepts/witme', title: 'Witme' },
	{ slug: 'intend/Concepts/yes-chef', title: 'YesChef' },
	{ slug: 'intend/about-this-commonplace', title: 'About this Commonplace' },
	{ slug: 'intend/abundance-facts', title: 'Abundance vs. Scarcity' },
	{
		slug: 'intend/anumaan-and-the-well-of-being',
		title: 'Anumaan and the Well of Being',
	},
	{
		slug: 'intend/automagically-prepend-front-matter',
		title: 'Automagically Prepend Front Matter',
	},
	{ slug: 'intend/bucky-fuller', title: 'R. Buckminster Fuller' },
	{
		slug: 'intend/building-this-commonplace',
		title: 'Building This Commonplace',
	},
	{
		slug: 'intend/bumps-in-the-foamy-dev-trail',
		title: 'Bumps in the Foamy Dev Trail',
	},
	{ slug: 'intend/business-to-easeness-plans', title: 'Business-to-Easeness' },
	{ slug: 'intend/chilean-chins-chilly', title: 'dust nugget preamble' },
	{ slug: 'intend/commonplace-book', title: 'Commonplace Book' },
	{ slug: 'intend/commonplace', title: 'Commonplace' },
	{ slug: 'intend/digital-garden', title: 'Digital Garden' },
	{ slug: 'intend/dust-crystal-v1', title: 'Dust Nugget v1' },
	{ slug: 'intend/dust-crystal-v2', title: 'Dust Nugget v2' },
	{ slug: 'intend/dust-crystal-v3', title: 'Dust Nugget v3' },
	{ slug: 'intend/dust-crystal-v4', title: 'Dust Nugget v4' },
	{ slug: 'intend/dust-nugget', title: 'Dust Nugget' },
	{ slug: 'intend/dust-nuggets-to-come', title: 'dust nuggets to come' },
	{ slug: 'intend/easeness-vs-business', title: 'Easeness vs. Business' },
	{ slug: 'intend/easeness', title: 'Easeness' },
	{
		slug: 'intend/easing-our-way-out-of-a-pandemic',
		title: 'Easing Our Way Out of a Pandemic',
	},
	{ slug: 'intend/evergreen-notes', title: 'Evergreen Notes' },
	{ slug: 'intend/fair-method', title: 'FAIR Method' },
	{ slug: 'intend/fear-or-joy', title: 'Fear or Joy' },
	{
		slug: 'intend/fil-and-the-well-of-being',
		title: 'Fil and the Well of Being',
	},
	{
		slug: 'intend/fine-grained-associations-yield-dense-linking',
		title: 'Fine grained associations yield dense linking',
	},
	{
		slug: 'intend/foam/examples/eg-excalidrawn',
		title: 'Excalidrawn Examples',
	},
	{
		slug: 'intend/foam/examples/eg-jsx-component-in-mdx',
		title: 'JSX Component in MDX Example',
	},
	{
		slug: 'intend/foam/examples/eg-next-image-component',
		title: 'Next Image Component Example',
	},
	{
		slug: 'intend/foam/examples/eg-numbered-footnotes',
		title: 'Numbered Footnotes',
	},
	{
		slug: 'intend/foam/examples/eg-remote-note',
		title: 'Remote MDX Note Example',
	},
	{
		slug: 'intend/foam/examples/eg-syntax-highlighting',
		title: 'Syntax Highlighting Example',
	},
	{ slug: 'intend/foam/examples/wiki-links', title: 'wiki-links' },
	{ slug: 'intend/foam/foam-inbox', title: 'Inbox' },
	{ slug: 'intend/foam/foam-readme', title: 'Readme' },
	{ slug: 'intend/foam/foamy-index', title: 'Foamy NextJS Index' },
	{ slug: 'intend/foam', title: 'Foam' },
	{ slug: 'intend/foamy-nextjs', title: 'Foamy NextJS Starter' },
	{ slug: 'intend/for-reasons', title: 'For Reasons' },
	{
		slug: 'intend/frontmatter-in-foamy-nextjs',
		title: 'Frontmatter In Foamy NextJS',
	},
	{ slug: 'intend/gratitude', title: 'Gratitude' },
	{ slug: 'intend/gravitation', title: 'gravitation' },
	{ slug: 'intend/how-i-built-this', title: 'How I Built This' },
	{
		slug: 'intend/how-to-case-links-in-a-commonplace',
		title: 'How to Case Links in a Commonplace',
	},
	{
		slug:
			'intend/ideas-become-more-densely-linked-as-the-association-among-them-become-more-finely-grained',
		title:
			'ideas-become-more-densely-linked-as-the-association-among-them-become-more-finely-grained',
	},
	{ slug: 'intend/inbox', title: 'Inbox' },
	{ slug: 'intend/intend-todo', title: 'Intend Todo' },
	{ slug: 'intend/nameless-todo', title: 'Nameless Todos' },
	{ slug: 'intend/nameless', title: 'Nameless' },
	{ slug: 'intend/notable-commonplace-books', title: 'Notable Commonplaces' },
	{ slug: 'intend/note', title: 'note' },
	{ slug: 'intend/ohmu', title: 'ohmu' },
	{
		slug: 'intend/ollie-and-the-well-of-being',
		title: 'Ollie and the Well of Being',
	},
	{ slug: 'intend/para-method', title: 'PARA method' },
	{ slug: 'intend/projects', title: 'projects' },
	{ slug: 'intend/second-brain', title: 'Second Brain' },
	{
		slug: 'intend/second-brains-i-have-tried-and-left',
		title: 'Second Brains I Have Tried And Left',
	},
	{ slug: 'intend/shake-it-easy-baby', title: 'Shake it Easy, Baby' },
	{ slug: 'intend/starvokar', title: 'Starvokar' },
	{ slug: 'intend/syntax-highlighting', title: 'syntax-highlighting' },
	{
		slug: 'intend/systems-of-decimal-octave-evolution',
		title: 'Systems of Decimal Octave Evolution',
	},
	{
		slug: 'intend/the-complexity-of-ancient-humanity',
		title: 'The Complexity of Ancient Humanity',
	},
	{
		slug: 'intend/the-story-of-my-second-brain',
		title: 'The Story of my Second Brain',
	},
	{ slug: 'intend/the-well-of-being-v2', title: 'The Well of Being v2' },
	{ slug: 'intend/the-well-of-being-v3', title: 'The Well of Being v3' },
	{ slug: 'intend/the-well-of-being', title: 'The Well of Being' },
	{ slug: 'intend/this-is-it-0', title: 'this is it' },
	{ slug: 'intend/this-is-it-1', title: 'this is it' },
	{ slug: 'intend/this-is-it-2', title: 'this is it' },
	{ slug: 'intend/this-is-it-3', title: 'this is it' },
	{ slug: 'intend/this-is-it-4', title: 'this is it' },
	{ slug: 'intend/this-is-it-5', title: 'this is it' },
	{ slug: 'intend/this-is-it', title: 'this is it' },
	{ slug: 'intend/toyls', title: 'toyls' },
	{
		slug: 'intend/well-of-being-characters',
		title: 'Well of Being Characters',
	},
	{ slug: 'intend/well-of-being-concepts', title: 'Well of Being Concepts' },
	{ slug: 'intend/who-i-am', title: 'Who I am' },
	{
		slug: 'intend/why-i-chose-foamy-nextjs',
		title: 'Why I Chose Foamy NextJS',
	},
	{ slug: 'intend/working-notes', title: 'Working Notes' },
	{ slug: 'intend/zettelkasten', title: 'Zettelkasten' },
	{ slug: 'intend', title: 'Intend' },
	{ slug: 'remember/0-the-fool', title: 'The Fool' },
	{ slug: 'remember/1-root', title: 'Root' },
	{
		slug: 'remember/12-rules-for-life',
		title: '12 Rules for Life - An Antidote to Chaos',
	},
	{ slug: 'remember/2-sacrum', title: 'Sacrum' },
	{
		slug: 'remember/20-steps-to-a-new-product',
		title: 'Snowpiercer - How to ship it continuously',
	},
	{
		slug: 'remember/20-steps-to-shipping-a-new-product',
		title: '20 Steps To Shipping A New Product',
	},
	{ slug: 'remember/2013-trends', title: 'Trends to Watch in 2013' },
	{ slug: 'remember/3-navel', title: 'Navel' },
	{ slug: 'remember/4-heart', title: 'Heart' },
	{ slug: 'remember/5-throat', title: 'Throat' },
	{ slug: 'remember/6-third-eye', title: 'Third Eye' },
	{ slug: 'remember/7-crown', title: 'Crown' },
	{ slug: 'remember/Devsign/browser-time', title: 'browser time' },
	{ slug: 'remember/Devsign/cli-terminal-cheatsheet', title: 'CLI Cheatsheet' },
	{ slug: 'remember/Devsign/code-snippets' },
	{
		slug: 'remember/Devsign/color-palette-blotter',
		title: 'Color Palette Blotter',
	},
	{
		slug: 'remember/Devsign/filter-undefined-nodes-out-of-an-array',
		title: 'Filter Falsy Nodes Out Of An Array',
	},
	{
		slug: 'remember/Devsign/hero-guidelines',
		title: 'Guidelines for constructing responsive-ready hero images',
	},
	{
		slug:
			'remember/Devsign/moving-my-development-environment-to-a-remote-server',
		title: 'Moving my development environment to a remote server',
	},
	{
		slug: 'remember/Devsign/my-journey-as-a-ux-designer',
		title: 'The Spectrum of UX',
	},
	{ slug: 'remember/Devsign/readme-devmo', title: 'README for teh codez' },
	{ slug: 'remember/Devsign/style-guide', title: 'Style Guide' },
	{
		slug: 'remember/Devsign/test-for-an-empty-object-in-javascript',
		title: 'Test For An Empty Object In Javascript',
	},
	{ slug: 'remember/Devsign/ux_you', title: 'UX and You' },
	{
		slug: 'remember/Devsign/vimhkal',
		title: 'VIM commands I Have Known and Loved',
	},
	{ slug: 'remember/Devsign/web-themes', title: 'Web Themes' },
	{
		slug: 'remember/a-dusty-rumination-on-time',
		title: 'A Dusty Rumination on Time',
	},
	{ slug: 'remember/abortion-facts-stats', title: 'Abortion Facts Stats' },
	{ slug: 'remember/about-bitcoin', title: 'Notes about Bitcoin' },
	{ slug: 'remember/adjectives-in-order', title: 'Description Generator' },
	{
		slug: 'remember/alan-watts-on-defining-nature',
		title: 'Alan Watts On Defining Nature',
	},
	{ slug: 'remember/astrology', title: 'Astrology' },
	{ slug: 'remember/axioms-and-postulates', title: 'Axioms and Postulates' },
	{ slug: 'remember/axioms', title: 'Axioms' },
	{ slug: 'remember/backyard-camping', title: 'Backyard Camping' },
	{ slug: 'remember/bazantar', title: 'Bazantar' },
	{ slug: 'remember/big-five-personality-models', title: 'Big Five' },
	{
		slug: 'remember/birth-date-fields',
		title: 'Happy birthday - Date of birth input field best practices',
	},
	{
		slug: 'remember/blockchain-bitcoin-and-cryptocurrency',
		title: 'Blockchain Basics',
	},
	{ slug: 'remember/blockchain-blotter', title: 'Blockchain Blotter' },
	{ slug: 'remember/blue-eyes', title: 'Blue eyes' },
	{ slug: 'remember/books', title: 'Books' },
	{ slug: 'remember/boolean-bounds', title: 'Boolean Bounds' },
	{ slug: 'remember/buddhism', title: 'Buddhism' },
	{
		slug: 'remember/clues-on-the-path-to-spirituality',
		title: 'Clues on the Path to Spirituality',
	},
	{
		slug: 'remember/convergence-of-study---modern-replacements',
		title: 'Convergence of Study - Modern Replacements',
	},
	{ slug: 'remember/crafting-the-kybalion-for-kids', title: 'Awaken to Dream' },
	{ slug: 'remember/cynosure', title: 'Cynosure' },
	{ slug: 'remember/daily-schedule', title: 'Daily Schedule' },
	{
		slug: 'remember/define-success-for-yourself',
		title: 'Define Success For Yourself',
	},
	{
		slug: 'remember/determinism-vs-teleonomy',
		title: 'Determinism vs. Teleonomy',
	},
	{ slug: 'remember/deuterostomes', title: 'Deuterostomes' },
	{ slug: 'remember/digital-philosophy', title: 'Digital Philosophy' },
	{
		slug: 'remember/distance-doesnt-matter-to-the-swift',
		title: 'Distance Doesnt Matter To The Swift',
	},
	{
		slug: 'remember/entropy-vs-information',
		title: 'Information vs. Entropy vs. Meaning',
	},
	{ slug: 'remember/etymology', title: 'etymology' },
	{
		slug: 'remember/extroversion-happens-when-you-can-ask-more-than-you-answer',
		title: 'Extroversion Happens When You Can Ask More Than You Answer',
	},
	{
		slug: 'remember/first-principles-of-quantum-mobility',
		title: 'First Principles of Quantum Mobility',
	},
	{
		slug: 'remember/flow-according-to-csikszentmihalyi',
		title: 'Flow according to Csikszentmihalyi',
	},
	{ slug: 'remember/food-in-iceland', title: 'Food In Iceland' },
	{ slug: 'remember/forbidden-words', title: 'Forbidden Words' },
	{ slug: 'remember/free-wont', title: "Free Won't" },
	{ slug: 'remember/gender-bridge', title: 'A Bridge for the Gender Gap' },
	{
		slug: 'remember/greek-mythology-pantheon-around-sisyphus',
		title: 'Sisyphus-centric Greek Mythology',
	},
	{ slug: 'remember/greek-pantheon', title: "Hesiod's Pantheon" },
	{
		slug: 'remember/growing-up-vs-waking-up',
		title: 'Growing Up Vs Waking Up',
	},
	{
		slug: 'remember/how-to-buy-a-train-ticket',
		title: 'How to buy a train ticket',
	},
	{ slug: 'remember/ikigai-finder', title: 'Ikigai Finder' },
	{ slug: 'remember/is-ignorance-bliss', title: 'Is ignorance bliss?' },
	{ slug: 'remember/is-this-hell', title: 'Is this hell?' },
	{
		slug: 'remember/its-never-too-early-for-immortality',
		title: "It's never too early for immortality.",
	},
	{
		slug: 'remember/journal/2021-04-09',
		title: 'Journal of Kerrbear 2021-04-09',
	},
	{ slug: 'remember/journal/two-way-linking', title: 'Mutualinks' },
	{
		slug: 'remember/just-doing-this-for-the-xp',
		title: 'The Simulation is Real',
	},
	{
		slug: 'remember/kill-guns',
		title: 'Disarmed, An Open Letter to Civilians Bearing Arms',
	},
	{ slug: 'remember/kybalion', title: 'Kybalion' },
	{ slug: 'remember/like-a-pole-axed-steer', title: 'Like A Pole Axed Steer' },
	{
		slug: 'remember/mac-osx-dev-setup-2014',
		title: 'Mac OSX Dev Environment Setup and Toolset',
	},
	{ slug: 'remember/markdown-sandbox', title: 'Markdown Sandbox' },
	{
		slug: 'remember/maslow-missed-a-few-tiers',
		title: 'Maslow missed a few tiers',
	},
	{ slug: 'remember/mathic-tricks', title: 'Metatronics and Mathic Tricks' },
	{
		slug: 'remember/megalofascism-mounts--all-apologies',
		title: 'All apologies. We are now subject to a megalofascist.',
	},
	{
		slug: 'remember/memes-themes-and-teams',
		title: 'Memes, Themes, and Teams',
	},
	{
		slug: 'remember/my-uncertainty-principle',
		title: 'My Uncertainty Principle',
	},
	{ slug: 'remember/naturopathy-log', title: 'Naturopathy Log' },
	{ slug: 'remember/noses-know', title: 'A nose knows not what it seeks' },
	{ slug: 'remember/notes-on-my-big-toe', title: 'Notes on My Big TOE' },
	{ slug: 'remember/olivella', title: 'Olivella' },
	{ slug: 'remember/on-destiny', title: 'On Destiny, Evolutionarily Speaking' },
	{ slug: 'remember/on-living-forever', title: 'Living Forever' },
	{ slug: 'remember/on-longevity', title: 'Longevity' },
	{
		slug: 'remember/on-nature-via-alan-watts',
		title: 'On Nature, via Alan Watts',
	},
	{ slug: 'remember/on-solipsism', title: 'On Solipsism' },
	{ slug: 'remember/one-to-one-mapping', title: 'One-to-one Mapping' },
	{ slug: 'remember/postulates', title: 'Postulates' },
	{
		slug: 'remember/sisyphus-differentiators',
		title: "Sisyphus' Differentiators",
	},
	{ slug: 'remember/sisyphys-saga', title: "Sisyphus' Saga" },
	{ slug: 'remember/stinky-startled-ants', title: 'Stinky Startled Ants' },
	{
		slug: 'remember/stop-fighting-about-energy',
		title: 'Stop Fighting About Energy',
	},
	{ slug: 'remember/tao-te-ching', title: 'Tao Te Ching' },
	{ slug: 'remember/tarot', title: 'Tarot' },
	{
		slug: 'remember/technoethics',
		title: "Technoethics - there's a shitcloud coming",
	},
	{ slug: 'remember/technoprayer', title: 'Technoprayer' },
	{ slug: 'remember/tenets', title: 'tenets' },
	{
		slug: 'remember/the-five-senses-and-some-25-more',
		title: 'the five senses and some 25 more',
	},
	{
		slug: 'remember/the-folly-of-prediction',
		title: 'The Time for Deadlines is Up',
	},
	{
		slug:
			'remember/the-majority-of-quantum-theorists-espouse-the-copenhagen-interpretation',
		title:
			'The majority of quantum theorists espouse the Copenhagen interpretation',
	},
	{
		slug: 'remember/the-new-science-of-consciousness',
		title: 'The New Science of Consciousness',
	},
	{
		slug: 'remember/the-only-things-that-matter-to-startups',
		title: 'The only things that matter to a startup',
	},
	{
		slug: 'remember/the-parameters-of-our-physical-reality',
		title: 'The Parameters of Physical Reality',
	},
	{ slug: 'remember/the-path-to-quality', title: 'The Path to Quality' },
	{ slug: 'remember/the-selfish-team', title: 'The Selfish Team' },
	{ slug: 'remember/the-simulation-is-real', title: 'The Simulation is Real' },
	{ slug: 'remember/the-way-of-zen', title: 'The Way of Zen' },
	{ slug: 'remember/tiresias-restored', title: 'Tiresias Restored' },
	{
		slug: 'remember/truth-a-la-william-james',
		title: 'Truth A La William James',
	},
	{ slug: 'remember/urban-living-2050', title: 'Urban living, Earth, 2050' },
	{ slug: 'remember/us-goes-fiat', title: 'Us Goes Fiat' },
	{
		slug: 'remember/usernames-neednt-be-unique-the-ideal-login',
		title: 'Usernames Neednt Be Unique - The Ideal Login',
	},
	{ slug: 'remember/ux/first-principles', title: 'First Principles' },
	{
		slug: 'remember/ux/front-end-dev-resources',
		title: 'Front End Dev Resources',
	},
	{
		slug: 'remember/ux/good-morning-solarcity',
		title: 'Good Morning Solarcity',
	},
	{
		slug: 'remember/ux/hero-guidelines',
		title: 'Guidelines for constructing responsive-ready hero images',
	},
	{ slug: 'remember/ux/holy-wonder', title: 'Holy Wonder' },
	{
		slug: 'remember/ux/how-to-build-great-software-teams',
		title: "We're trying to build great software (teams)",
	},
	{ slug: 'remember/ux/ie8-equals-user-error', title: 'Ie8 Equals User Error' },
	{
		slug: 'remember/ux/interaction-design-inspiration',
		title: 'Interaction Design Inspiration',
	},
	{
		slug: 'remember/ux/marissa-mayers-3-rule-of-app-design',
		title: "Marissa Mayer's 3 Rules of App Design",
	},
	{ slug: 'remember/ux/meeting-room-ui', title: 'MeetingRoom API the verbs' },
	{ slug: 'remember/ux/meteor-basics', title: 'Meteor Basics' },
	{
		slug: 'remember/ux/my-journey-as-a-ux-designer',
		title: 'The Spectrum of UX',
	},
	{ slug: 'remember/ux/notes-on-design', title: 'Notes On Design' },
	{ slug: 'remember/ux/notes-on-the-hig', title: 'Notes on the HIG' },
	{
		slug: 'remember/ux/omotenashi',
		title: 'Omotenashi - The Art of Hospitality',
	},
	{
		slug: 'remember/ux/on-fonts-and-typefaces',
		title: 'On Fonts and Typefaces',
	},
	{ slug: 'remember/ux/on-grids-and-layouts', title: 'On Grids and Layouts' },
	{ slug: 'remember/ux/papetyping', title: 'Papetyping' },
	{
		slug: 'remember/ux/person-reaction-interest-matrix',
		title: 'Person Reaction Interest Matrix',
	},
	{ slug: 'remember/ux/raybot-readme', title: 'Raybot' },
	{
		slug: 'remember/ux/shibumi---zen-design',
		title: 'Principles of Zen Design',
	},
	{ slug: 'remember/ux/skills-of-a-devsigner', title: 'Skills of a Devsigner' },
	{
		slug: 'remember/ux/snowpiercer',
		title: 'Snowpiercer - Ship it perpetually',
	},
	{
		slug: 'remember/ux/talkers-vs.-doers',
		title: '20121117 Talkers Vs. Doers',
	},
	{
		slug: 'remember/ux/technology-should-be-magical',
		title: 'Technology should be magical',
	},
	{ slug: 'remember/ux-and-you', title: 'UX and You' },
	{ slug: 'remember/uxioms-spec', title: 'UXioms spec' },
	{ slug: 'remember/uxioms', title: 'Uxioms' },
	{ slug: 'remember/vedic-science', title: 'Vedic Science' },
	{
		slug: 'remember/walking-the-path-without-knowing-the-path',
		title: 'Walking the path without knowing the path',
	},
	{ slug: 'remember/web-4.0', title: 'Web 4.0' },
	{
		slug: 'remember/where-do-people-want-to-be-faster',
		title: 'Where Do People Want To Be Faster',
	},
	{ slug: 'remember/who-sang-first', title: 'The First Song' },
	{ slug: 'remember/whole-earth-totem', title: 'Whole Earth Totem' },
	{
		slug: 'remember/wrote-and-published-this-on-my-phone',
		title: 'Automatically publish posts from your iPhone to your Jekyll blog',
	},
	{ slug: 'remember/yoga-sutra', title: "Patanjali's Yoga Sutra" },
	{ slug: 'remember/zuben-elgenubi', title: 'Zuben Elgenubi' },
	{ slug: 'remember', title: 'Remember' },
	{ slug: 'todo', title: 'Todo' },
]
